// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHmk2bPGUcBq3x-LaVyIQ_r_yWOvBZ0_I',
    appId: '1:1049545801330:web:106566f7fbb7ea01d18ceb',
    messagingSenderId: '1049545801330',
    projectId: 'trivia-ia-app',
    authDomain: 'trivia-ia-app.firebaseapp.com',
    storageBucket: 'trivia-ia-app.firebasestorage.app',
    measurementId: 'G-710TFCJ411',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQFi-tg_-glqSiX4Yomemsazs-E6CmwEU',
    appId: '1:1049545801330:android:2aae921fcdb556ccd18ceb',
    messagingSenderId: '1049545801330',
    projectId: 'trivia-ia-app',
    storageBucket: 'trivia-ia-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4S8T8uxIZyWF37swoRVUYbAUvclDcFJw',
    appId: '1:1049545801330:ios:72ccbf254b44ba1bd18ceb',
    messagingSenderId: '1049545801330',
    projectId: 'trivia-ia-app',
    storageBucket: 'trivia-ia-app.firebasestorage.app',
    iosBundleId: 'com.example.triviaIaFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4S8T8uxIZyWF37swoRVUYbAUvclDcFJw',
    appId: '1:1049545801330:ios:72ccbf254b44ba1bd18ceb',
    messagingSenderId: '1049545801330',
    projectId: 'trivia-ia-app',
    storageBucket: 'trivia-ia-app.firebasestorage.app',
    iosBundleId: 'com.example.triviaIaFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHmk2bPGUcBq3x-LaVyIQ_r_yWOvBZ0_I',
    appId: '1:1049545801330:web:b22d3cf9ae3c9e11d18ceb',
    messagingSenderId: '1049545801330',
    projectId: 'trivia-ia-app',
    authDomain: 'trivia-ia-app.firebaseapp.com',
    storageBucket: 'trivia-ia-app.firebasestorage.app',
    measurementId: 'G-BLLTDVLELY',
  );
}
