module.exports = {
  // difficulty_1 -> niveles 1-3. Cultura general, sin necesidad de aficion previa.
  d1: [
    {q: "¿En qué ciudad se encuentra el Museo del Prado?", options: ["Barcelona", "Madrid", "Sevilla", "Valencia"], answerIndex: 1},
    {q: "¿Cuáles son los tres colores primarios en la pintura tradicional?", options: ["Verde, naranja y violeta", "Blanco, negro y gris", "Rojo, azul y amarillo", "Rojo, verde y azul"], answerIndex: 2},
    {q: "¿Qué técnica pictórica usa pigmentos diluidos en agua sobre papel?", options: ["Acuarela", "Óleo", "Fresco", "Grabado"], answerIndex: 0},
    {q: "¿Qué herramienta usa un pintor para mezclar sus colores?", options: ["El cincel", "El compás", "El torno", "La paleta"], answerIndex: 3},
    {q: "¿Qué museo de París tiene una pirámide de vidrio en su entrada?", options: ["El Louvre", "El Orsay", "El Pompidou", "El Rodin"], answerIndex: 0},
    {q: "¿Qué material se usa tradicionalmente para esculpir estatuas clásicas?", options: ["Plástico", "Vidrio", "Mármol", "Papel"], answerIndex: 2},
    {q: "¿Qué torre italiana es famosa por estar inclinada?", options: ["La Torre de Pisa", "La Torre de Londres", "La Torre Eiffel", "El Big Ben"], answerIndex: 0},
    {q: "¿Cómo se llama una pintura que representa a una persona?", options: ["Paisaje", "Bodegón", "Mural", "Retrato"], answerIndex: 3},
    {q: "¿Cómo se llama una pintura que representa objetos inanimados como frutas y jarrones?", options: ["Bodegón", "Retrato", "Paisaje", "Autorretrato"], answerIndex: 0},
    {q: "¿En qué país nació Pablo Picasso?", options: ["Francia", "Italia", "España", "Portugal"], answerIndex: 2},
    {q: "¿Qué pintor neerlandés pintó la serie de \"Los girasoles\"?", options: ["Rembrandt", "Vincent van Gogh", "Johannes Vermeer", "Piet Mondrian"], answerIndex: 1},
    {q: "¿Qué es un mural?", options: ["Una escultura de bronce", "Un dibujo a lápiz", "Una pintura realizada sobre una pared", "Una fotografía antigua"], answerIndex: 2},
    {q: "¿Qué significan las siglas del museo MoMA de Nueva York?", options: ["Museo de Arte Moderno", "Museo Metropolitano de Arte", "Museo de Obras Maestras Americanas", "Museo de Oriente y Medio Asia"], answerIndex: 0},
    {q: "¿Qué herramienta usa un escultor para tallar la piedra?", options: ["El pincel", "La espátula", "El rodillo", "El cincel"], answerIndex: 3},
    {q: "¿Qué periodo de Picasso siguió a su periodo azul?", options: ["El periodo verde", "El periodo rosa", "El periodo amarillo", "El periodo gris"], answerIndex: 1},
    {q: "¿Qué arte tradicional japonés consiste en doblar papel?", options: ["Ikebana", "Kabuki", "Origami", "Sumi-e"], answerIndex: 2},
  ],

  // difficulty_2 -> niveles 4-7. Requiere cierto interes por el tema.
  d2: [
    {q: "¿Qué pintor francés lideró el movimiento fauvista junto a André Derain?", options: ["Henri Matisse", "Paul Signac", "Georges Braque", "Raoul Dufy"], answerIndex: 0},
    {q: "¿Qué museo de San Petersburgo es uno de los más grandes del mundo?", options: ["El Pushkin", "El Hermitage", "El Tretiakov", "El Russo"], answerIndex: 1},
    {q: "¿Qué pintor inglés es célebre por sus paisajes marinos y su tratamiento de la luz?", options: ["John Constable", "Thomas Gainsborough", "J. M. W. Turner", "William Hogarth"], answerIndex: 2},
    {q: "¿Qué técnica mural consiste en pintar sobre yeso todavía húmedo?", options: ["El fresco", "El temple", "El esmalte", "La encáustica"], answerIndex: 0},
    {q: "¿Qué escultor y pintor colombiano es famoso por sus figuras de volúmenes exagerados?", options: ["Oswaldo Guayasamín", "Fernando Botero", "Wifredo Lam", "Rufino Tamayo"], answerIndex: 1},
    {q: "¿Qué movimiento artístico italiano de 1909 exaltaba la velocidad y la máquina?", options: ["El futurismo", "El divisionismo", "La pintura metafísica", "El novecento"], answerIndex: 0},
    {q: "¿Qué pintor francés dio nombre al impresionismo con \"Impresión, sol naciente\"?", options: ["Édouard Manet", "Camille Pissarro", "Alfred Sisley", "Claude Monet"], answerIndex: 3},
    {q: "¿Qué artista estadounidense popularizó la técnica del goteo o \"dripping\"?", options: ["Mark Rothko", "Jackson Pollock", "Willem de Kooning", "Franz Kline"], answerIndex: 1},
    {q: "¿Qué pintor español creó la serie de las Pinturas Negras?", options: ["Francisco de Goya", "Joaquín Sorolla", "Bartolomé Esteban Murillo", "José de Ribera"], answerIndex: 0},
    {q: "¿En qué ciudad se encuentra el Museo Van Gogh?", options: ["Bruselas", "Ámsterdam", "Róterdam", "Amberes"], answerIndex: 1},
    {q: "¿Qué pintor italiano del Renacimiento pintó \"La escuela de Atenas\"?", options: ["Rafael Sanzio", "Andrea Mantegna", "Pietro Perugino", "Paolo Uccello"], answerIndex: 0},
    {q: "¿Qué estilo arquitectónico medieval se caracteriza por arcos apuntados y grandes vitrales?", options: ["El románico", "El bizantino", "El gótico", "El plateresco"], answerIndex: 2},
    {q: "¿Qué pintor neerlandés es conocido por sus interiores domésticos iluminados por una ventana lateral?", options: ["Frans Hals", "Jan Steen", "Pieter de Hooch", "Johannes Vermeer"], answerIndex: 3},
    {q: "¿Qué artista japonés creó la estampa \"La gran ola de Kanagawa\"?", options: ["Katsushika Hokusai", "Utagawa Hiroshige", "Kitagawa Utamaro", "Tōshūsai Sharaku"], answerIndex: 0},
    {q: "¿Qué galería de Londres alberga arte moderno y contemporáneo en una antigua central eléctrica?", options: ["La National Gallery", "La Tate Modern", "La Royal Academy", "La Serpentine"], answerIndex: 1},
    {q: "¿Qué corriente de los años 60 tomó imágenes de la publicidad y la cultura de masas?", options: ["El arte pop", "El informalismo", "El acción-pintura", "El constructivismo"], answerIndex: 0},
    {q: "¿Qué pintor de origen bielorruso es conocido por sus escenas oníricas y su color intenso?", options: ["Marc Chagall", "Chaim Soutine", "Amedeo Modigliani", "Jules Pascin"], answerIndex: 0},
    {q: "¿Qué museo de Florencia alberga \"El nacimiento de Venus\"?", options: ["El Palacio Pitti", "El Bargello", "La Galería Uffizi", "La Academia"], answerIndex: 2},
    {q: "¿Qué artista suizo es famoso por sus esculturas de figuras humanas alargadas y delgadas?", options: ["Jean Tinguely", "Alberto Giacometti", "Hans Arp", "Paul Klee"], answerIndex: 1},
    {q: "¿Qué pintor postimpresionista francés se instaló en Tahití y retrató a sus habitantes?", options: ["Paul Gauguin", "Henri de Toulouse-Lautrec", "Georges Seurat", "Odilon Redon"], answerIndex: 0},
    {q: "¿Qué pintor francés es considerado precursor del cubismo por su tratamiento geométrico de la naturaleza?", options: ["Édouard Vuillard", "Pierre Bonnard", "Paul Cézanne", "Maurice Denis"], answerIndex: 2},
    {q: "¿Qué monumento de la India es un mausoleo de mármol blanco?", options: ["El Fuerte Rojo", "El Templo Dorado", "El Qutab Minar", "El Taj Mahal"], answerIndex: 3},
    {q: "¿Qué técnica consiste en pegar recortes y materiales diversos sobre una superficie?", options: ["El collage", "El esgrafiado", "La serigrafía", "El puntillismo"], answerIndex: 0},
    {q: "¿Qué pintor belga acompañó una pipa con la frase \"Esto no es una pipa\"?", options: ["Paul Delvaux", "René Magritte", "James Ensor", "Constant Permeke"], answerIndex: 1},
    {q: "¿Qué artista del Renacimiento escribía sus cuadernos en escritura especular, de derecha a izquierda?", options: ["Leonardo da Vinci", "Sandro Botticelli", "Donatello", "Filippo Brunelleschi"], answerIndex: 0},
    {q: "¿Qué arquitecto estadounidense diseñó la Casa de la Cascada?", options: ["Louis Sullivan", "Philip Johnson", "Frank Lloyd Wright", "Eero Saarinen"], answerIndex: 2},
    {q: "¿Qué técnica de pintura mezcla los pigmentos con cera caliente?", options: ["La encáustica", "El gouache", "El pastel", "La aguada"], answerIndex: 0},
  ],

  // difficulty_3 -> niveles 8-10. Conocimiento especializado.
  d3: [
    {q: "¿Qué pintora del Barroco italiano es autora de \"Judit decapitando a Holofernes\"?", options: ["Sofonisba Anguissola", "Artemisia Gentileschi", "Lavinia Fontana", "Elisabetta Sirani"], answerIndex: 1},
    {q: "¿Qué grupo expresionista alemán fundado en Dresde en 1905 incluyó a Ernst Ludwig Kirchner?", options: ["Der Blaue Reiter", "Die Brücke", "Neue Sachlichkeit", "Der Sturm"], answerIndex: 1},
    {q: "¿Qué escuela de diseño alemana fundada por Walter Gropius en 1919 unió arte, artesanía e industria?", options: ["La Bauhaus", "La Werkbund", "La Secesión", "La Vkhutemas"], answerIndex: 0},
    {q: "¿Qué pintor italiano realizó los frescos de la Capilla de los Scrovegni en Padua?", options: ["Cimabue", "Duccio", "Giotto", "Simone Martini"], answerIndex: 2},
    {q: "¿Qué artista introdujo el concepto de \"ready-made\" con obras como \"La Fuente\"?", options: ["Marcel Duchamp", "Man Ray", "Francis Picabia", "Kurt Schwitters"], answerIndex: 0},
    {q: "¿Qué término designa la técnica de difuminar los contornos con transiciones suaves, asociada a Leonardo?", options: ["Impasto", "Grisalla", "Sfumato", "Veladura"], answerIndex: 2},
    {q: "¿Qué pintora estadounidense es conocida por sus flores en primer plano y paisajes de Nuevo México?", options: ["Mary Cassatt", "Georgia O'Keeffe", "Helen Frankenthaler", "Lee Krasner"], answerIndex: 1},
    {q: "¿A qué escultor de la Grecia clásica se atribuye el \"Discóbolo\"?", options: ["Fidias", "Policleto", "Praxíteles", "Mirón"], answerIndex: 3},
    {q: "¿Qué corriente de los años 60 reduce la obra a formas geométricas simples y a la repetición?", options: ["El minimalismo", "El arte cinético", "El arte póvera", "El op art"], answerIndex: 0},
    {q: "¿Qué técnica de grabado cubre una plancha metálica con barniz y la muerde con ácido?", options: ["La xilografía", "El aguafuerte", "La litografía", "La punta seca"], answerIndex: 1},
    {q: "¿Qué arquitecto diseñó el Museo Guggenheim de Bilbao?", options: ["Santiago Calatrava", "Norman Foster", "Frank Gehry", "Rafael Moneo"], answerIndex: 2},
    {q: "¿Qué pintor del Neoclasicismo francés pintó \"La muerte de Marat\"?", options: ["Jacques-Louis David", "Jean-Auguste-Dominique Ingres", "Antoine-Jean Gros", "Théodore Géricault"], answerIndex: 0},
    {q: "¿Qué movimiento británico del siglo XIX buscaba recuperar el detalle y el color anteriores a Rafael?", options: ["El esteticismo", "El prerrafaelismo", "Arts and Crafts", "El academicismo victoriano"], answerIndex: 1},
    {q: "¿Qué pintor del Renacimiento veneciano es autor de la enigmática \"La tempestad\"?", options: ["Tiziano", "Tintoretto", "Giorgione", "Veronés"], answerIndex: 2},
    {q: "¿Qué artista alemán contemporáneo emplea plomo, paja y ceniza en sus obras de gran formato?", options: ["Gerhard Richter", "Anselm Kiefer", "Sigmar Polke", "Georg Baselitz"], answerIndex: 1},
    {q: "¿Qué término designa la pintura mural realizada sobre yeso ya seco?", options: ["Buon fresco", "Pintura al secco", "Estuco", "Terracota"], answerIndex: 1},
    {q: "¿Qué escultor francés del siglo XIX creó \"Los burgueses de Calais\"?", options: ["Aristide Maillol", "Jean-Baptiste Carpeaux", "Auguste Rodin", "Antoine Bourdelle"], answerIndex: 2},
  ],
};
