module.exports = {
  d1: [
    {q: "¿Cuál es el único satélite natural de la Tierra?", options: ["Ío", "La Luna", "Fobos", "Titán"], answerIndex: 1},
    {q: "¿Qué órgano usamos principalmente para respirar?", options: ["El hígado", "Los pulmones", "Los riñones", "El estómago"], answerIndex: 1},
    {q: "¿Cuál es la fórmula química del agua?", options: ["O2", "H2O", "CO2", "NaCl"], answerIndex: 1},
    {q: "¿A qué temperatura hierve el agua a nivel del mar?", options: ["80 °C", "100 °C", "50 °C", "150 °C"], answerIndex: 1},
    {q: "¿A qué temperatura se congela el agua a nivel del mar?", options: ["-10 °C", "10 °C", "5 °C", "0 °C"], answerIndex: 3},
    {q: "¿Qué fuerza nos mantiene sobre la superficie de la Tierra?", options: ["La fricción", "La inercia", "La gravedad", "El magnetismo"], answerIndex: 2},
    {q: "¿Cuántas patas tiene un insecto adulto?", options: ["Seis", "Cuatro", "Diez", "Ocho"], answerIndex: 0},
    {q: "¿Qué gas es el más abundante en la atmósfera terrestre?", options: ["Oxígeno", "Nitrógeno", "Hidrógeno", "Dióxido de carbono"], answerIndex: 1},
    {q: "¿Qué planeta del sistema solar tiene los anillos más visibles?", options: ["Júpiter", "Saturno", "Urano", "Neptuno"], answerIndex: 1},
    {q: "¿Qué sentido está asociado a la lengua?", options: ["El gusto", "El olfato", "El oído", "El tacto"], answerIndex: 0},
    {q: "¿Qué instrumento se usa para observar objetos muy pequeños?", options: ["El estetoscopio", "El periscopio", "El microscopio", "El telescopio"], answerIndex: 2},
    {q: "¿Cuál es el animal terrestre más grande de la actualidad?", options: ["La jirafa", "El elefante africano", "El rinoceronte blanco", "El hipopótamo"], answerIndex: 1},
    {q: "¿Qué tipo de energía produce un panel solar?", options: ["Energía sonora", "Energía química", "Energía nuclear", "Energía eléctrica"], answerIndex: 3},
    {q: "¿Cuál es el órgano más extenso del cuerpo humano?", options: ["El intestino", "El hígado", "La piel", "El cerebro"], answerIndex: 2},
    {q: "¿Qué animal de esta lista es un mamífero?", options: ["El delfín", "El tiburón", "El cocodrilo", "La tortuga"], answerIndex: 0},
    {q: "¿Cuántas cámaras tiene el corazón humano?", options: ["Tres", "Cuatro", "Cinco", "Dos"], answerIndex: 1},
  ],

  d2: [
    {q: "¿Cuál es la unidad de medida de la resistencia eléctrica?", options: ["El amperio", "El voltio", "El ohmio", "El vatio"], answerIndex: 2},
    {q: "¿Qué órgano produce la insulina?", options: ["El bazo", "El páncreas", "El hígado", "La tiroides"], answerIndex: 1},
    {q: "¿Qué tipo de roca se forma al enfriarse el magma?", options: ["Ígnea", "Sedimentaria", "Metamórfica", "Caliza"], answerIndex: 0},
    {q: "¿Qué sabio griego enunció el principio de flotación de los cuerpos?", options: ["Arquímedes", "Euclides", "Pitágoras", "Tales de Mileto"], answerIndex: 0},
    {q: "¿Cuál es el metal más abundante en la corteza terrestre?", options: ["Magnesio", "Hierro", "Aluminio", "Cobre"], answerIndex: 2},
    {q: "¿Qué parte de la neurona transmite el impulso hacia otras células?", options: ["La mielina", "El soma", "Las dendritas", "El axón"], answerIndex: 3},
    {q: "¿Qué proceso convierte un líquido en gas por debajo de su punto de ebullición?", options: ["La sublimación", "La evaporación", "La solidificación", "La condensación"], answerIndex: 1},
    {q: "¿Qué elemento químico tiene el símbolo Fe?", options: ["Hierro", "Fósforo", "Fermio", "Flúor"], answerIndex: 0},
    {q: "¿Cuál es el planeta más grande del sistema solar?", options: ["Saturno", "Neptuno", "Júpiter", "Urano"], answerIndex: 2},
    {q: "¿Qué tipo de enlace químico comparte electrones entre dos átomos?", options: ["Metálico", "Puente de hidrógeno", "Iónico", "Covalente"], answerIndex: 3},
    {q: "¿Qué órganos filtran la sangre y producen la orina?", options: ["El bazo", "El hígado", "Los riñones", "Los pulmones"], answerIndex: 2},
    {q: "¿Qué vitamina previene el escorbuto?", options: ["Vitamina B12", "Vitamina C", "Vitamina K", "Vitamina A"], answerIndex: 1},
    {q: "¿En qué capa de la atmósfera ocurren los fenómenos meteorológicos?", options: ["Estratosfera", "Troposfera", "Termosfera", "Mesosfera"], answerIndex: 1},
    {q: "¿Qué gas noble emite luz rojiza en los letreros luminosos?", options: ["Neón", "Helio", "Kriptón", "Argón"], answerIndex: 0},
    {q: "¿Cuál es la unidad de frecuencia en el Sistema Internacional?", options: ["El kelvin", "El julio", "El hercio", "El pascal"], answerIndex: 2},
    {q: "¿Qué instrumento mide la presión atmosférica?", options: ["El anemómetro", "El higrómetro", "El pluviómetro", "El barómetro"], answerIndex: 3},
    {q: "¿Qué proteína transporta el oxígeno en la sangre?", options: ["La queratina", "La albúmina", "La hemoglobina", "El colágeno"], answerIndex: 2},
    {q: "¿Qué científico formuló las leyes de la herencia estudiando guisantes?", options: ["Carl Linneo", "Robert Koch", "Louis Pasteur", "Gregor Mendel"], answerIndex: 3},
    {q: "¿Qué estado de la materia tiene forma y volumen definidos?", options: ["Gaseoso", "Sólido", "Plasma", "Líquido"], answerIndex: 1},
    {q: "¿Qué parte de la planta realiza principalmente la fotosíntesis?", options: ["El tallo", "La raíz", "La flor", "La hoja"], answerIndex: 3},
    {q: "¿Cuál es el elemento más abundante del universo?", options: ["Hidrógeno", "Oxígeno", "Carbono", "Helio"], answerIndex: 0},
    {q: "¿Qué tipo de energía posee un cuerpo debido a su movimiento?", options: ["Cinética", "Térmica", "Química", "Potencial"], answerIndex: 0},
    {q: "¿Qué ácido predomina en el jugo gástrico del estómago?", options: ["Ácido sulfúrico", "Ácido clorhídrico", "Ácido cítrico", "Ácido acético"], answerIndex: 1},
    {q: "¿Cuánto tarda aproximadamente la luz del Sol en llegar a la Tierra?", options: ["8 minutos", "8 días", "8 horas", "8 segundos"], answerIndex: 0},
    {q: "¿Qué reproducción no requiere la unión de gametos?", options: ["Alogamia", "Asexual", "Cruzada", "Sexual"], answerIndex: 1},
    {q: "¿Qué tipo de onda es el sonido?", options: ["Estacionaria transversal", "Mecánica longitudinal", "Gravitacional", "Electromagnética"], answerIndex: 1},
    {q: "¿Qué escala se usa tradicionalmente para medir la magnitud de un terremoto?", options: ["La escala Mohs", "La escala Kelvin", "La escala Beaufort", "La escala de Richter"], answerIndex: 3},
  ],

  d3: [
    {q: "¿Qué ley relaciona presión y volumen de un gas a temperatura constante?", options: ["La ley de Dalton", "La ley de Gay-Lussac", "La ley de Charles", "La ley de Boyle"], answerIndex: 3},
    {q: "¿Qué orgánulo celular se encarga de sintetizar las proteínas?", options: ["El lisosoma", "El peroxisoma", "El centriolo", "El ribosoma"], answerIndex: 3},
    {q: "¿Cuál es el valor aproximado de la constante de Avogadro?", options: ["1,602 × 10^-19", "6,022 × 10^23", "3,14 × 10^8", "9,81 × 10^5"], answerIndex: 1},
    {q: "¿Qué tipo de radiación tiene mayor poder de penetración?", options: ["Gamma", "Alfa", "Beta", "Ultravioleta"], answerIndex: 0},
    {q: "¿Qué ciclo bioquímico también se conoce como ciclo del ácido cítrico?", options: ["El ciclo de Calvin", "El ciclo de la urea", "El ciclo de Krebs", "La glucólisis"], answerIndex: 2},
    {q: "¿Qué partícula es responsable de mediar la fuerza electromagnética?", options: ["El bosón W", "El neutrino", "El gluón", "El fotón"], answerIndex: 3},
    {q: "¿Qué científico propuso el modelo atómico del \"budín de pasas\"?", options: ["J. J. Thomson", "John Dalton", "James Chadwick", "Ernest Rutherford"], answerIndex: 0},
    {q: "¿Qué ley de la termodinámica introduce el concepto de entropía?", options: ["La primera ley", "La tercera ley", "La ley cero", "La segunda ley"], answerIndex: 3},
    {q: "¿Qué tipo de interacción mantiene unidas las dos hebras del ADN?", options: ["Puentes de hidrógeno", "Fuerzas metálicas", "Enlaces iónicos", "Enlaces covalentes"], answerIndex: 0},
    {q: "¿Cuál es la unidad de actividad radiactiva en el Sistema Internacional?", options: ["El curio", "El gray", "El sievert", "El becquerel"], answerIndex: 3},
    {q: "¿Qué enzima sintetiza ARN a partir de una hebra molde de ADN?", options: ["La ADN ligasa", "La transcriptasa inversa", "La ARN polimerasa", "La helicasa"], answerIndex: 2},
    {q: "¿Qué metal tiene el punto de fusión más alto?", options: ["Tungsteno", "Platino", "Osmio", "Titanio"], answerIndex: 0},
    {q: "¿Cómo se llama la temperatura por encima de la cual un gas no puede licuarse solo con presión?", options: ["Temperatura crítica", "Temperatura de Curie", "Punto triple", "Cero absoluto"], answerIndex: 0},
    {q: "¿Qué teoría describe la interacción fuerte entre quarks?", options: ["La teoría electrodébil", "La relatividad general", "La electrodinámica cuántica", "La cromodinámica cuántica"], answerIndex: 3},
    {q: "¿Qué tipo de división celular da origen a los gametos?", options: ["La meiosis", "La citocinesis", "La amitosis", "La mitosis"], answerIndex: 0},
    {q: "¿Qué físico formuló las ecuaciones que unifican electricidad y magnetismo?", options: ["Michael Faraday", "André-Marie Ampère", "James Clerk Maxwell", "Heinrich Hertz"], answerIndex: 2},
    {q: "¿Qué fenómeno explica que la luz de las galaxias lejanas se desplace hacia el rojo?", options: ["La expansión del universo", "La absorción interestelar", "La refracción atmosférica", "El efecto fotoeléctrico"], answerIndex: 0},
  ],
};
