module.exports = {
  d1: [
    {q: "¿Cuál es el único satélite natural de la Tierra?", options: ["Fobos", "La Luna", "Ío", "Titán"], answerIndex: 1},
    {q: "¿Qué órgano usamos principalmente para respirar?", options: ["El hígado", "El estómago", "Los pulmones", "Los riñones"], answerIndex: 2},
    {q: "¿Cuál es la fórmula química del agua?", options: ["H2O", "CO2", "O2", "NaCl"], answerIndex: 0},
    {q: "¿A qué temperatura hierve el agua a nivel del mar?", options: ["50 °C", "80 °C", "100 °C", "150 °C"], answerIndex: 2},
    {q: "¿A qué temperatura se congela el agua a nivel del mar?", options: ["0 °C", "-10 °C", "5 °C", "10 °C"], answerIndex: 0},
    {q: "¿Qué fuerza nos mantiene sobre la superficie de la Tierra?", options: ["El magnetismo", "La gravedad", "La fricción", "La inercia"], answerIndex: 1},
    {q: "¿Cuántas patas tiene un insecto adulto?", options: ["Cuatro", "Ocho", "Diez", "Seis"], answerIndex: 3},
    {q: "¿Qué gas es el más abundante en la atmósfera terrestre?", options: ["Oxígeno", "Nitrógeno", "Dióxido de carbono", "Hidrógeno"], answerIndex: 1},
    {q: "¿Qué planeta del sistema solar tiene los anillos más visibles?", options: ["Júpiter", "Urano", "Saturno", "Neptuno"], answerIndex: 2},
    {q: "¿Qué sentido está asociado a la lengua?", options: ["El gusto", "El olfato", "El tacto", "El oído"], answerIndex: 0},
    {q: "¿Qué instrumento se usa para observar objetos muy pequeños?", options: ["El telescopio", "El periscopio", "El estetoscopio", "El microscopio"], answerIndex: 3},
    {q: "¿Cuál es el animal terrestre más grande de la actualidad?", options: ["El rinoceronte blanco", "El elefante africano", "La jirafa", "El hipopótamo"], answerIndex: 1},
    {q: "¿Qué tipo de energía produce un panel solar?", options: ["Energía eléctrica", "Energía nuclear", "Energía química", "Energía sonora"], answerIndex: 0},
    {q: "¿Cuál es el órgano más extenso del cuerpo humano?", options: ["El hígado", "El intestino", "La piel", "El cerebro"], answerIndex: 2},
    {q: "¿Qué animal de esta lista es un mamífero?", options: ["El tiburón", "El cocodrilo", "La tortuga", "El delfín"], answerIndex: 3},
    {q: "¿Cuántas cámaras tiene el corazón humano?", options: ["Dos", "Tres", "Cuatro", "Cinco"], answerIndex: 2},
  ],

  d2: [
    {q: "¿Cuál es la unidad de medida de la resistencia eléctrica?", options: ["El ohmio", "El vatio", "El amperio", "El voltio"], answerIndex: 0},
    {q: "¿Qué órgano produce la insulina?", options: ["El hígado", "El páncreas", "El bazo", "La tiroides"], answerIndex: 1},
    {q: "¿Qué tipo de roca se forma al enfriarse el magma?", options: ["Sedimentaria", "Metamórfica", "Ígnea", "Caliza"], answerIndex: 2},
    {q: "¿Qué sabio griego enunció el principio de flotación de los cuerpos?", options: ["Arquímedes", "Pitágoras", "Euclides", "Tales de Mileto"], answerIndex: 0},
    {q: "¿Cuál es el metal más abundante en la corteza terrestre?", options: ["Hierro", "Cobre", "Aluminio", "Magnesio"], answerIndex: 2},
    {q: "¿Qué parte de la neurona transmite el impulso hacia otras células?", options: ["Las dendritas", "El axón", "El soma", "La mielina"], answerIndex: 1},
    {q: "¿Qué proceso convierte un líquido en gas por debajo de su punto de ebullición?", options: ["La evaporación", "La sublimación", "La condensación", "La solidificación"], answerIndex: 0},
    {q: "¿Qué elemento químico tiene el símbolo Fe?", options: ["Flúor", "Fósforo", "Fermio", "Hierro"], answerIndex: 3},
    {q: "¿Cuál es el planeta más grande del sistema solar?", options: ["Saturno", "Júpiter", "Neptuno", "Urano"], answerIndex: 1},
    {q: "¿Qué tipo de enlace químico comparte electrones entre dos átomos?", options: ["Iónico", "Metálico", "Covalente", "Puente de hidrógeno"], answerIndex: 2},
    {q: "¿Qué órganos filtran la sangre y producen la orina?", options: ["Los riñones", "Los pulmones", "El hígado", "El bazo"], answerIndex: 0},
    {q: "¿Qué vitamina previene el escorbuto?", options: ["Vitamina A", "Vitamina C", "Vitamina K", "Vitamina B12"], answerIndex: 1},
    {q: "¿En qué capa de la atmósfera ocurren los fenómenos meteorológicos?", options: ["Estratosfera", "Mesosfera", "Troposfera", "Termosfera"], answerIndex: 2},
    {q: "¿Qué gas noble emite luz rojiza en los letreros luminosos?", options: ["Argón", "Helio", "Kriptón", "Neón"], answerIndex: 3},
    {q: "¿Cuál es la unidad de frecuencia en el Sistema Internacional?", options: ["El hercio", "El julio", "El pascal", "El kelvin"], answerIndex: 0},
    {q: "¿Qué instrumento mide la presión atmosférica?", options: ["El higrómetro", "El barómetro", "El anemómetro", "El pluviómetro"], answerIndex: 1},
    {q: "¿Qué proteína transporta el oxígeno en la sangre?", options: ["La albúmina", "El colágeno", "La hemoglobina", "La queratina"], answerIndex: 2},
    {q: "¿Qué científico formuló las leyes de la herencia estudiando guisantes?", options: ["Louis Pasteur", "Robert Koch", "Carl Linneo", "Gregor Mendel"], answerIndex: 3},
    {q: "¿Qué estado de la materia tiene forma y volumen definidos?", options: ["Sólido", "Líquido", "Gaseoso", "Plasma"], answerIndex: 0},
    {q: "¿Qué parte de la planta realiza principalmente la fotosíntesis?", options: ["La raíz", "La hoja", "El tallo", "La flor"], answerIndex: 1},
    {q: "¿Cuál es el elemento más abundante del universo?", options: ["Helio", "Oxígeno", "Hidrógeno", "Carbono"], answerIndex: 2},
    {q: "¿Qué tipo de energía posee un cuerpo debido a su movimiento?", options: ["Potencial", "Térmica", "Química", "Cinética"], answerIndex: 3},
    {q: "¿Qué ácido predomina en el jugo gástrico del estómago?", options: ["Ácido clorhídrico", "Ácido sulfúrico", "Ácido cítrico", "Ácido acético"], answerIndex: 0},
    {q: "¿Cuánto tarda aproximadamente la luz del Sol en llegar a la Tierra?", options: ["8 segundos", "8 minutos", "8 horas", "8 días"], answerIndex: 1},
    {q: "¿Qué reproducción no requiere la unión de gametos?", options: ["Sexual", "Cruzada", "Asexual", "Alogamia"], answerIndex: 2},
    {q: "¿Qué tipo de onda es el sonido?", options: ["Electromagnética", "Gravitacional", "Estacionaria transversal", "Mecánica longitudinal"], answerIndex: 3},
    {q: "¿Qué escala se usa tradicionalmente para medir la magnitud de un terremoto?", options: ["La escala de Richter", "La escala Beaufort", "La escala Kelvin", "La escala Mohs"], answerIndex: 0},
  ],

  d3: [
    {q: "¿Qué ley relaciona presión y volumen de un gas a temperatura constante?", options: ["La ley de Boyle", "La ley de Charles", "La ley de Gay-Lussac", "La ley de Dalton"], answerIndex: 0},
    {q: "¿Qué orgánulo celular se encarga de sintetizar las proteínas?", options: ["El lisosoma", "El ribosoma", "El peroxisoma", "El centriolo"], answerIndex: 1},
    {q: "¿Cuál es el valor aproximado de la constante de Avogadro?", options: ["3,14 × 10^8", "9,81 × 10^5", "6,022 × 10^23", "1,602 × 10^-19"], answerIndex: 2},
    {q: "¿Qué tipo de radiación tiene mayor poder de penetración?", options: ["Alfa", "Beta", "Ultravioleta", "Gamma"], answerIndex: 3},
    {q: "¿Qué ciclo bioquímico también se conoce como ciclo del ácido cítrico?", options: ["El ciclo de Krebs", "El ciclo de Calvin", "El ciclo de la urea", "La glucólisis"], answerIndex: 0},
    {q: "¿Qué partícula es responsable de mediar la fuerza electromagnética?", options: ["El gluón", "El fotón", "El bosón W", "El neutrino"], answerIndex: 1},
    {q: "¿Qué científico propuso el modelo atómico del \"budín de pasas\"?", options: ["Ernest Rutherford", "John Dalton", "J. J. Thomson", "James Chadwick"], answerIndex: 2},
    {q: "¿Qué ley de la termodinámica introduce el concepto de entropía?", options: ["La ley cero", "La primera ley", "La tercera ley", "La segunda ley"], answerIndex: 3},
    {q: "¿Qué tipo de interacción mantiene unidas las dos hebras del ADN?", options: ["Puentes de hidrógeno", "Enlaces iónicos", "Enlaces covalentes", "Fuerzas metálicas"], answerIndex: 0},
    {q: "¿Cuál es la unidad de actividad radiactiva en el Sistema Internacional?", options: ["El curio", "El becquerel", "El sievert", "El gray"], answerIndex: 1},
    {q: "¿Qué enzima sintetiza ARN a partir de una hebra molde de ADN?", options: ["La ADN ligasa", "La helicasa", "La ARN polimerasa", "La transcriptasa inversa"], answerIndex: 2},
    {q: "¿Qué metal tiene el punto de fusión más alto?", options: ["Platino", "Titanio", "Osmio", "Tungsteno"], answerIndex: 3},
    {q: "¿Cómo se llama la temperatura por encima de la cual un gas no puede licuarse solo con presión?", options: ["Temperatura crítica", "Punto triple", "Temperatura de Curie", "Cero absoluto"], answerIndex: 0},
    {q: "¿Qué teoría describe la interacción fuerte entre quarks?", options: ["La electrodinámica cuántica", "La cromodinámica cuántica", "La teoría electrodébil", "La relatividad general"], answerIndex: 1},
    {q: "¿Qué tipo de división celular da origen a los gametos?", options: ["La mitosis", "La citocinesis", "La meiosis", "La amitosis"], answerIndex: 2},
    {q: "¿Qué físico formuló las ecuaciones que unifican electricidad y magnetismo?", options: ["Michael Faraday", "André-Marie Ampère", "Heinrich Hertz", "James Clerk Maxwell"], answerIndex: 3},
    {q: "¿Qué fenómeno explica que la luz de las galaxias lejanas se desplace hacia el rojo?", options: ["La expansión del universo", "La refracción atmosférica", "La absorción interestelar", "El efecto fotoeléctrico"], answerIndex: 0},
  ],
};
