module.exports = {
  d1: [
    {q: "¿Qué princesa de Disney pierde una zapatilla de cristal?", options: ["Blancanieves", "Cenicienta", "Aurora", "Bella"], answerIndex: 1},
    {q: "¿De qué color es el ogro protagonista de \"Shrek\"?", options: ["Gris", "Marrón", "Azul", "Verde"], answerIndex: 3},
    {q: "¿Qué actor protagonizó \"Forrest Gump\"?", options: ["Tom Hanks", "Kevin Costner", "Harrison Ford", "Robin Williams"], answerIndex: 0},
    {q: "¿Qué tipo de animal es Nemo en la película de Pixar?", options: ["Una tortuga", "Un pez payaso", "Un delfín", "Un tiburón"], answerIndex: 1},
    {q: "¿Qué actriz protagonizó \"Titanic\" junto a Leonardo DiCaprio?", options: ["Julia Roberts", "Cameron Diaz", "Nicole Kidman", "Kate Winslet"], answerIndex: 3},
    {q: "¿Qué superhéroe tiene como identidad secreta a Bruce Wayne?", options: ["Linterna Verde", "Superman", "Flash", "Batman"], answerIndex: 3},
    {q: "¿Qué superhéroe tiene como identidad secreta a Clark Kent?", options: ["Batman", "Hulk", "Superman", "Aquaman"], answerIndex: 2},
    {q: "¿Qué maestro pequeño y verde entrena a los Jedi en \"Star Wars\"?", options: ["R2-D2", "Yoda", "Chewbacca", "Jabba"], answerIndex: 1},
    {q: "¿Qué película de Disney tiene una princesa con poderes de hielo llamada Elsa?", options: ["Frozen", "Valiente", "Enredados", "Moana"], answerIndex: 0},
    {q: "¿Cómo se llama el premio más importante del cine estadounidense?", options: ["El Goya", "El Globo de Oro", "El Óscar", "El BAFTA"], answerIndex: 2},
    {q: "¿Qué actor interpretó a Harry Potter en las películas?", options: ["Tom Felton", "Daniel Radcliffe", "Elijah Wood", "Rupert Grint"], answerIndex: 1},
    {q: "¿En qué ciudad vive Spider-Man?", options: ["Metrópolis", "Los Ángeles", "Chicago", "Nueva York"], answerIndex: 3},
    {q: "¿Cuántas películas componen la trilogía original de \"El Señor de los Anillos\"?", options: ["Tres", "Cinco", "Dos", "Cuatro"], answerIndex: 0},
    {q: "¿Qué película narra la historia de un niño que se queda solo en casa en Navidad?", options: ["Elf", "Mi pobre angelito", "Polar Express", "El Grinch"], answerIndex: 1},
    {q: "¿Qué estudio produjo la película \"El Rey León\"?", options: ["Paramount", "Universal", "Disney", "Warner Bros."], answerIndex: 2},
    {q: "¿Qué personaje de \"Star Wars\" es un robot pequeño con forma de barril?", options: ["BB-8", "IG-11", "C-3PO", "R2-D2"], answerIndex: 3},
  ],

  d2: [
    {q: "¿Qué director dirigió \"El club de la pelea\"?", options: ["Darren Aronofsky", "Paul Thomas Anderson", "Spike Jonze", "David Fincher"], answerIndex: 3},
    {q: "¿Qué director es conocido por \"El resplandor\" y \"La naranja mecánica\"?", options: ["Stanley Kubrick", "William Friedkin", "Sidney Lumet", "Roman Polanski"], answerIndex: 0},
    {q: "¿Qué actriz protagonizó \"La La Land\"?", options: ["Anne Hathaway", "Natalie Portman", "Emma Stone", "Amy Adams"], answerIndex: 2},
    {q: "¿Qué película de Studio Ghibli sigue a una niña llamada Chihiro?", options: ["El viaje de Chihiro", "El castillo ambulante", "Mi vecino Totoro", "La princesa Mononoke"], answerIndex: 0},
    {q: "¿Qué cineasta japonés fundó Studio Ghibli junto a Isao Takahata?", options: ["Makoto Shinkai", "Hayao Miyazaki", "Mamoru Hosoda", "Satoshi Kon"], answerIndex: 1},
    {q: "¿Qué director surcoreano dirigió \"Parásitos\"?", options: ["Kim Ki-duk", "Park Chan-wook", "Lee Chang-dong", "Bong Joon-ho"], answerIndex: 3},
    {q: "¿Qué película de 1972 dirigida por Coppola retrata a la familia Corleone?", options: ["El Padrino", "Uno de los nuestros", "Scarface", "Casino"], answerIndex: 0},
    {q: "¿Qué película de Ridley Scott tiene a Russell Crowe como el general Máximo?", options: ["Troya", "El reino de los cielos", "Gladiador", "Alejandro Magno"], answerIndex: 2},
    {q: "¿Qué compositor italiano creó la música de \"El bueno, el feo y el malo\"?", options: ["Nino Rota", "Piero Piccioni", "Riz Ortolani", "Ennio Morricone"], answerIndex: 3},
    {q: "¿En qué país se rodó principalmente la saga de \"El Señor de los Anillos\"?", options: ["Irlanda", "Escocia", "Canadá", "Nueva Zelanda"], answerIndex: 3},
    {q: "¿Qué actor interpretó a Hannibal Lecter en \"El silencio de los inocentes\"?", options: ["Ian McKellen", "Gary Oldman", "Michael Caine", "Anthony Hopkins"], answerIndex: 3},
    {q: "¿Qué película de Martin Scorsese sigue el ascenso de Henry Hill en la mafia?", options: ["Taxi Driver", "Casino", "Buenos muchachos", "El irlandés"], answerIndex: 2},
    {q: "¿Qué director japonés dirigió \"Los siete samuráis\"?", options: ["Yasujirō Ozu", "Kenji Mizoguchi", "Takeshi Kitano", "Akira Kurosawa"], answerIndex: 3},
    {q: "¿Qué película de 1975 dirigida por Spielberg trata sobre un tiburón blanco?", options: ["Mar abierto", "Orca", "Abyss", "Tiburón"], answerIndex: 3},
    {q: "¿Qué actriz interpretó a Katniss Everdeen en \"Los Juegos del Hambre\"?", options: ["Shailene Woodley", "Kristen Stewart", "Saoirse Ronan", "Jennifer Lawrence"], answerIndex: 3},
    {q: "¿Qué película de Pixar sigue a un robot que limpia una Tierra abandonada?", options: ["WALL·E", "Up", "Los Increíbles", "Ratatouille"], answerIndex: 0},
    {q: "¿Qué actor español ganó el Óscar por \"No es país para viejos\"?", options: ["Eduardo Noriega", "Luis Tosar", "Antonio Banderas", "Javier Bardem"], answerIndex: 3},
    {q: "¿Qué director español dirigió \"Todo sobre mi madre\"?", options: ["Carlos Saura", "Juan Antonio Bayona", "Pedro Almodóvar", "Alejandro Amenábar"], answerIndex: 2},
    {q: "¿Qué película de Frank Darabont transcurre en la prisión de Shawshank?", options: ["La milla verde", "El expreso de medianoche", "Escape de Alcatraz", "Sueño de fuga"], answerIndex: 3},
    {q: "¿Qué directora dirigió \"Lost in Translation\"?", options: ["Sofia Coppola", "Jane Campion", "Kathryn Bigelow", "Greta Gerwig"], answerIndex: 0},
    {q: "¿Qué película mexicana de Alfonso Cuarón ganó el Óscar a Mejor Película Extranjera en 2019?", options: ["Y tu mamá también", "Roma", "Amores perros", "Güeros"], answerIndex: 1},
    {q: "¿Qué actor interpretó a Vito Corleone en \"El Padrino\" de 1972?", options: ["Robert Duvall", "Marlon Brando", "Robert De Niro", "James Caan"], answerIndex: 1},
    {q: "¿Qué director dirigió \"Taxi Driver\"?", options: ["Michael Cimino", "John Cassavetes", "Brian De Palma", "Martin Scorsese"], answerIndex: 3},
    {q: "¿Qué película de animación japonesa de 1988 dirigida por Katsuhiro Otomo es un clásico cyberpunk?", options: ["Akira", "Ghost in the Shell", "Paprika", "Perfect Blue"], answerIndex: 0},
    {q: "¿Qué actriz interpretó a Sarah Connor en la primera película de \"Terminator\"?", options: ["Jamie Lee Curtis", "Linda Hamilton", "Carrie Fisher", "Sigourney Weaver"], answerIndex: 1},
    {q: "¿Qué película de superhéroes de 2019 cerró la saga del Infinito de Marvel?", options: ["Spider-Man: Lejos de casa", "Black Panther", "Capitana Marvel", "Avengers: Endgame"], answerIndex: 3},
    {q: "¿Qué actriz ha ganado el mayor número de Óscar de actuación en la historia?", options: ["Meryl Streep", "Katharine Hepburn", "Bette Davis", "Ingrid Bergman"], answerIndex: 1},
  ],

  d3: [
    {q: "¿Qué película alemana de 1927 dirigida por Fritz Lang es un clásico de la ciencia ficción muda?", options: ["Nosferatu", "El gabinete del doctor Caligari", "M, el vampiro de Düsseldorf", "Metrópolis"], answerIndex: 3},
    {q: "¿Qué director sueco dirigió \"El séptimo sello\"?", options: ["Lasse Hallström", "Ingmar Bergman", "Bo Widerberg", "Roy Andersson"], answerIndex: 1},
    {q: "¿Qué película de Federico Fellini sigue a un periodista por la Roma de la alta sociedad?", options: ["La dolce vita", "Ocho y medio", "Amarcord", "La strada"], answerIndex: 0},
    {q: "¿Qué cineasta soviético teorizó el montaje intelectual y dirigió \"El acorazado Potemkin\"?", options: ["Serguéi Eisenstein", "Lev Kuleshov", "Vsévolod Pudovkin", "Dziga Vertov"], answerIndex: 0},
    {q: "¿Qué director francés de la Nouvelle Vague dirigió \"Sin aliento\"?", options: ["Claude Chabrol", "François Truffaut", "Éric Rohmer", "Jean-Luc Godard"], answerIndex: 3},
    {q: "¿Qué película de Orson Welles de 1941 es considerada una de las mejores de la historia?", options: ["Sed de mal", "El tercer hombre", "Ciudadano Kane", "La dama de Shanghái"], answerIndex: 2},
    {q: "¿Qué director italiano dirigió \"Ladrón de bicicletas\", obra clave del neorrealismo?", options: ["Vittorio De Sica", "Michelangelo Antonioni", "Luchino Visconti", "Roberto Rossellini"], answerIndex: 0},
    {q: "¿Qué cineasta español, ligado al surrealismo, dirigió \"Un perro andaluz\"?", options: ["Luis Buñuel", "Víctor Erice", "Juan Antonio Bardem", "Carlos Saura"], answerIndex: 0},
    {q: "¿Qué película de Andréi Tarkovski adapta la novela de Stanisław Lem sobre un planeta oceánico?", options: ["El espejo", "Andréi Rubliov", "Solaris", "Stalker"], answerIndex: 2},
    {q: "¿Qué director de fotografía mexicano ganó tres premios Óscar consecutivos?", options: ["Rodrigo Prieto", "Gabriel Figueroa", "Emmanuel Lubezki", "Guillermo Navarro"], answerIndex: 2},
    {q: "¿Qué película de Michael Curtiz de 1942 transcurre en Marruecos durante la Segunda Guerra Mundial?", options: ["Sabotaje", "El halcón maltés", "Tener y no tener", "Casablanca"], answerIndex: 3},
    {q: "¿Qué movimiento cinematográfico danés impulsado por Lars von Trier estableció un \"voto de castidad\"?", options: ["Cinema Novo", "Nuevo Cine Alemán", "Free Cinema", "Dogma 95"], answerIndex: 3},
    {q: "¿Qué actriz sueca protagonizó \"Casablanca\" junto a Humphrey Bogart?", options: ["Ingrid Bergman", "Greta Garbo", "Marlene Dietrich", "Lauren Bacall"], answerIndex: 0},
    {q: "¿Qué película muda de Charles Chaplin incluye la escena en la que se come un zapato?", options: ["La quimera del oro", "El chico", "Luces de la ciudad", "Tiempos modernos"], answerIndex: 0},
    {q: "¿Qué festival de cine entrega la Palma de Oro?", options: ["Cannes", "San Sebastián", "Berlín", "Venecia"], answerIndex: 0},
    {q: "¿Qué director ganó el Óscar a Mejor Director por \"La vida de Pi\"?", options: ["Danny Boyle", "Alfonso Cuarón", "Ang Lee", "Alejandro González Iñárritu"], answerIndex: 2},
    {q: "¿Qué película francesa de Jean Renoir de 1939 es una sátira de la sociedad de su época?", options: ["El salario del miedo", "Hiroshima mon amour", "Los 400 golpes", "La regla del juego"], answerIndex: 3},
  ],
};
