module.exports = {
  d1: [
    {q: "¿Qué princesa de Disney pierde una zapatilla de cristal?", options: ["Blancanieves", "Cenicienta", "Aurora", "Bella"], answerIndex: 1},
    {q: "¿De qué color es el ogro protagonista de \"Shrek\"?", options: ["Verde", "Azul", "Marrón", "Gris"], answerIndex: 0},
    {q: "¿Qué actor protagonizó \"Forrest Gump\"?", options: ["Kevin Costner", "Robin Williams", "Tom Hanks", "Harrison Ford"], answerIndex: 2},
    {q: "¿Qué tipo de animal es Nemo en la película de Pixar?", options: ["Un delfín", "Una tortuga", "Un tiburón", "Un pez payaso"], answerIndex: 3},
    {q: "¿Qué actriz protagonizó \"Titanic\" junto a Leonardo DiCaprio?", options: ["Kate Winslet", "Nicole Kidman", "Julia Roberts", "Cameron Diaz"], answerIndex: 0},
    {q: "¿Qué superhéroe tiene como identidad secreta a Bruce Wayne?", options: ["Superman", "Batman", "Flash", "Linterna Verde"], answerIndex: 1},
    {q: "¿Qué superhéroe tiene como identidad secreta a Clark Kent?", options: ["Batman", "Aquaman", "Superman", "Hulk"], answerIndex: 2},
    {q: "¿Qué maestro pequeño y verde entrena a los Jedi en \"Star Wars\"?", options: ["Chewbacca", "R2-D2", "Jabba", "Yoda"], answerIndex: 3},
    {q: "¿Qué película de Disney tiene una princesa con poderes de hielo llamada Elsa?", options: ["Frozen", "Moana", "Enredados", "Valiente"], answerIndex: 0},
    {q: "¿Cómo se llama el premio más importante del cine estadounidense?", options: ["El Globo de Oro", "El Óscar", "El BAFTA", "El Goya"], answerIndex: 1},
    {q: "¿Qué actor interpretó a Harry Potter en las películas?", options: ["Rupert Grint", "Elijah Wood", "Daniel Radcliffe", "Tom Felton"], answerIndex: 2},
    {q: "¿En qué ciudad vive Spider-Man?", options: ["Chicago", "Los Ángeles", "Metrópolis", "Nueva York"], answerIndex: 3},
    {q: "¿Cuántas películas componen la trilogía original de \"El Señor de los Anillos\"?", options: ["Tres", "Dos", "Cuatro", "Cinco"], answerIndex: 0},
    {q: "¿Qué película narra la historia de un niño que se queda solo en casa en Navidad?", options: ["Elf", "Mi pobre angelito", "El Grinch", "Polar Express"], answerIndex: 1},
    {q: "¿Qué estudio produjo la película \"El Rey León\"?", options: ["Warner Bros.", "Universal", "Disney", "Paramount"], answerIndex: 2},
    {q: "¿Qué personaje de \"Star Wars\" es un robot pequeño con forma de barril?", options: ["C-3PO", "BB-8", "IG-11", "R2-D2"], answerIndex: 3},
  ],

  d2: [
    {q: "¿Qué director dirigió \"El club de la pelea\"?", options: ["David Fincher", "Darren Aronofsky", "Paul Thomas Anderson", "Spike Jonze"], answerIndex: 0},
    {q: "¿Qué director es conocido por \"El resplandor\" y \"La naranja mecánica\"?", options: ["Roman Polanski", "Stanley Kubrick", "Sidney Lumet", "William Friedkin"], answerIndex: 1},
    {q: "¿Qué actriz protagonizó \"La La Land\"?", options: ["Anne Hathaway", "Natalie Portman", "Emma Stone", "Amy Adams"], answerIndex: 2},
    {q: "¿Qué película de Studio Ghibli sigue a una niña llamada Chihiro?", options: ["Mi vecino Totoro", "La princesa Mononoke", "El castillo ambulante", "El viaje de Chihiro"], answerIndex: 3},
    {q: "¿Qué cineasta japonés fundó Studio Ghibli junto a Isao Takahata?", options: ["Hayao Miyazaki", "Mamoru Hosoda", "Satoshi Kon", "Makoto Shinkai"], answerIndex: 0},
    {q: "¿Qué director surcoreano dirigió \"Parásitos\"?", options: ["Park Chan-wook", "Bong Joon-ho", "Kim Ki-duk", "Lee Chang-dong"], answerIndex: 1},
    {q: "¿Qué película de 1972 dirigida por Coppola retrata a la familia Corleone?", options: ["Uno de los nuestros", "Casino", "El Padrino", "Scarface"], answerIndex: 2},
    {q: "¿Qué película de Ridley Scott tiene a Russell Crowe como el general Máximo?", options: ["Troya", "Alejandro Magno", "El reino de los cielos", "Gladiador"], answerIndex: 3},
    {q: "¿Qué compositor italiano creó la música de \"El bueno, el feo y el malo\"?", options: ["Ennio Morricone", "Nino Rota", "Riz Ortolani", "Piero Piccioni"], answerIndex: 0},
    {q: "¿En qué país se rodó principalmente la saga de \"El Señor de los Anillos\"?", options: ["Irlanda", "Nueva Zelanda", "Escocia", "Canadá"], answerIndex: 1},
    {q: "¿Qué actor interpretó a Hannibal Lecter en \"El silencio de los inocentes\"?", options: ["Gary Oldman", "Ian McKellen", "Anthony Hopkins", "Michael Caine"], answerIndex: 2},
    {q: "¿Qué película de Martin Scorsese sigue el ascenso de Henry Hill en la mafia?", options: ["Casino", "Taxi Driver", "El irlandés", "Buenos muchachos"], answerIndex: 3},
    {q: "¿Qué director japonés dirigió \"Los siete samuráis\"?", options: ["Akira Kurosawa", "Yasujirō Ozu", "Kenji Mizoguchi", "Takeshi Kitano"], answerIndex: 0},
    {q: "¿Qué película de 1975 dirigida por Spielberg trata sobre un tiburón blanco?", options: ["Abyss", "Tiburón", "Mar abierto", "Orca"], answerIndex: 1},
    {q: "¿Qué actriz interpretó a Katniss Everdeen en \"Los Juegos del Hambre\"?", options: ["Shailene Woodley", "Kristen Stewart", "Jennifer Lawrence", "Saoirse Ronan"], answerIndex: 2},
    {q: "¿Qué película de Pixar sigue a un robot que limpia una Tierra abandonada?", options: ["Up", "Ratatouille", "Los Increíbles", "WALL·E"], answerIndex: 3},
    {q: "¿Qué actor español ganó el Óscar por \"No es país para viejos\"?", options: ["Javier Bardem", "Antonio Banderas", "Eduardo Noriega", "Luis Tosar"], answerIndex: 0},
    {q: "¿Qué director español dirigió \"Todo sobre mi madre\"?", options: ["Alejandro Amenábar", "Pedro Almodóvar", "Carlos Saura", "Juan Antonio Bayona"], answerIndex: 1},
    {q: "¿Qué película de Frank Darabont transcurre en la prisión de Shawshank?", options: ["La milla verde", "Escape de Alcatraz", "Sueño de fuga", "El expreso de medianoche"], answerIndex: 2},
    {q: "¿Qué directora dirigió \"Lost in Translation\"?", options: ["Kathryn Bigelow", "Greta Gerwig", "Jane Campion", "Sofia Coppola"], answerIndex: 3},
    {q: "¿Qué película mexicana de Alfonso Cuarón ganó el Óscar a Mejor Película Extranjera en 2019?", options: ["Roma", "Amores perros", "Y tu mamá también", "Güeros"], answerIndex: 0},
    {q: "¿Qué actor interpretó a Vito Corleone en \"El Padrino\" de 1972?", options: ["Robert De Niro", "Marlon Brando", "James Caan", "Robert Duvall"], answerIndex: 1},
    {q: "¿Qué director dirigió \"Taxi Driver\"?", options: ["Brian De Palma", "Michael Cimino", "Martin Scorsese", "John Cassavetes"], answerIndex: 2},
    {q: "¿Qué película de animación japonesa de 1988 dirigida por Katsuhiro Otomo es un clásico cyberpunk?", options: ["Ghost in the Shell", "Perfect Blue", "Paprika", "Akira"], answerIndex: 3},
    {q: "¿Qué actriz interpretó a Sarah Connor en la primera película de \"Terminator\"?", options: ["Linda Hamilton", "Sigourney Weaver", "Carrie Fisher", "Jamie Lee Curtis"], answerIndex: 0},
    {q: "¿Qué película de superhéroes de 2019 cerró la saga del Infinito de Marvel?", options: ["Capitana Marvel", "Avengers: Endgame", "Spider-Man: Lejos de casa", "Black Panther"], answerIndex: 1},
    {q: "¿Qué actriz ha ganado el mayor número de Óscar de actuación en la historia?", options: ["Meryl Streep", "Bette Davis", "Katharine Hepburn", "Ingrid Bergman"], answerIndex: 2},
  ],

  d3: [
    {q: "¿Qué película alemana de 1927 dirigida por Fritz Lang es un clásico de la ciencia ficción muda?", options: ["Metrópolis", "Nosferatu", "El gabinete del doctor Caligari", "M, el vampiro de Düsseldorf"], answerIndex: 0},
    {q: "¿Qué director sueco dirigió \"El séptimo sello\"?", options: ["Lasse Hallström", "Ingmar Bergman", "Roy Andersson", "Bo Widerberg"], answerIndex: 1},
    {q: "¿Qué película de Federico Fellini sigue a un periodista por la Roma de la alta sociedad?", options: ["Amarcord", "Ocho y medio", "La dolce vita", "La strada"], answerIndex: 2},
    {q: "¿Qué cineasta soviético teorizó el montaje intelectual y dirigió \"El acorazado Potemkin\"?", options: ["Dziga Vertov", "Vsévolod Pudovkin", "Lev Kuleshov", "Serguéi Eisenstein"], answerIndex: 3},
    {q: "¿Qué director francés de la Nouvelle Vague dirigió \"Sin aliento\"?", options: ["Jean-Luc Godard", "François Truffaut", "Claude Chabrol", "Éric Rohmer"], answerIndex: 0},
    {q: "¿Qué película de Orson Welles de 1941 es considerada una de las mejores de la historia?", options: ["Sed de mal", "Ciudadano Kane", "El tercer hombre", "La dama de Shanghái"], answerIndex: 1},
    {q: "¿Qué director italiano dirigió \"Ladrón de bicicletas\", obra clave del neorrealismo?", options: ["Roberto Rossellini", "Luchino Visconti", "Vittorio De Sica", "Michelangelo Antonioni"], answerIndex: 2},
    {q: "¿Qué cineasta español, ligado al surrealismo, dirigió \"Un perro andaluz\"?", options: ["Carlos Saura", "Víctor Erice", "Juan Antonio Bardem", "Luis Buñuel"], answerIndex: 3},
    {q: "¿Qué película de Andréi Tarkovski adapta la novela de Stanisław Lem sobre un planeta oceánico?", options: ["Solaris", "Stalker", "El espejo", "Andréi Rubliov"], answerIndex: 0},
    {q: "¿Qué director de fotografía mexicano ganó tres premios Óscar consecutivos?", options: ["Rodrigo Prieto", "Emmanuel Lubezki", "Gabriel Figueroa", "Guillermo Navarro"], answerIndex: 1},
    {q: "¿Qué película de Michael Curtiz de 1942 transcurre en Marruecos durante la Segunda Guerra Mundial?", options: ["Tener y no tener", "El halcón maltés", "Casablanca", "Sabotaje"], answerIndex: 2},
    {q: "¿Qué movimiento cinematográfico danés impulsado por Lars von Trier estableció un \"voto de castidad\"?", options: ["Free Cinema", "Cinema Novo", "Nuevo Cine Alemán", "Dogma 95"], answerIndex: 3},
    {q: "¿Qué actriz sueca protagonizó \"Casablanca\" junto a Humphrey Bogart?", options: ["Ingrid Bergman", "Greta Garbo", "Lauren Bacall", "Marlene Dietrich"], answerIndex: 0},
    {q: "¿Qué película muda de Charles Chaplin incluye la escena en la que se come un zapato?", options: ["Luces de la ciudad", "La quimera del oro", "Tiempos modernos", "El chico"], answerIndex: 1},
    {q: "¿Qué festival de cine entrega la Palma de Oro?", options: ["Venecia", "Berlín", "Cannes", "San Sebastián"], answerIndex: 2},
    {q: "¿Qué director ganó el Óscar a Mejor Director por \"La vida de Pi\"?", options: ["Danny Boyle", "Alejandro González Iñárritu", "Alfonso Cuarón", "Ang Lee"], answerIndex: 3},
    {q: "¿Qué película francesa de Jean Renoir de 1939 es una sátira de la sociedad de su época?", options: ["La regla del juego", "Los 400 golpes", "El salario del miedo", "Hiroshima mon amour"], answerIndex: 0},
  ],
};
