module.exports = {
  d1: [
    {q: "¿Con qué parte del cuerpo no puede tocar el balón un jugador de campo en el fútbol?", options: ["Las manos", "La cabeza", "El pecho", "Los muslos"], answerIndex: 0},
    {q: "¿Cuántos tiempos tiene un partido de fútbol reglamentario?", options: ["Uno", "Dos", "Tres", "Cuatro"], answerIndex: 1},
    {q: "¿Cuántos minutos dura cada tiempo de un partido de fútbol?", options: ["30", "40", "45", "50"], answerIndex: 2},
    {q: "¿Qué deporte se juega con un balón naranja y un aro elevado?", options: ["Balonmano", "Voleibol", "Rugby", "Baloncesto"], answerIndex: 3},
    {q: "¿En qué deporte se usa un bate, una pelota y se corre entre bases?", options: ["Béisbol", "Críquet", "Golf", "Hockey"], answerIndex: 0},
    {q: "¿De qué color es la tarjeta con la que se expulsa a un jugador de fútbol?", options: ["Amarilla", "Roja", "Azul", "Verde"], answerIndex: 1},
    {q: "¿En qué deporte compiten Rafael Nadal y Roger Federer?", options: ["Bádminton", "Pádel", "Tenis", "Squash"], answerIndex: 2},
    {q: "¿Qué deporte se practica sobre hielo con un disco y bastones?", options: ["Curling", "Patinaje artístico", "Bobsleigh", "Hockey sobre hielo"], answerIndex: 3},
    {q: "¿En qué deporte se anota un \"home run\"?", options: ["Béisbol", "Fútbol americano", "Baloncesto", "Rugby"], answerIndex: 0},
    {q: "¿En qué país se disputa el torneo de tenis de Roland Garros?", options: ["Reino Unido", "Francia", "Australia", "Estados Unidos"], answerIndex: 1},
    {q: "¿Qué animal se monta en las competencias de equitación?", options: ["El camello", "El toro", "El caballo", "El elefante"], answerIndex: 2},
    {q: "¿Con qué se golpea la pelota en el golf?", options: ["Una raqueta", "Un bate", "Un mazo", "Un palo"], answerIndex: 3},
    {q: "¿Qué deporte se practica con un balón ovalado y cascos en Estados Unidos?", options: ["Fútbol americano", "Rugby", "Lacrosse", "Balonmano"], answerIndex: 0},
    {q: "¿Cuántas ruedas tiene una bicicleta de carreras?", options: ["Una", "Dos", "Tres", "Cuatro"], answerIndex: 1},
    {q: "¿Qué se necesita cruzar para ganar una carrera de atletismo?", options: ["La línea de salida", "El carril central", "La línea de meta", "La zona de relevos"], answerIndex: 2},
    {q: "¿En qué deporte destacó Michael Jordan?", options: ["Béisbol", "Fútbol americano", "Atletismo", "Baloncesto"], answerIndex: 3},
  ],

  d2: [
    {q: "¿En qué ciudad se celebraron los Juegos Olímpicos de 2020, aplazados a 2021?", options: ["Tokio", "París", "Pekín", "Seúl"], answerIndex: 0},
    {q: "¿Cuántos jugadores tiene en el campo un equipo de rugby union?", options: ["13", "15", "11", "9"], answerIndex: 1},
    {q: "¿Qué selección ganó la Eurocopa de 2021?", options: ["Inglaterra", "España", "Italia", "Francia"], answerIndex: 2},
    {q: "¿Qué club español ha ganado más Copas de Europa y Champions League?", options: ["Barcelona", "Atlético de Madrid", "Valencia", "Real Madrid"], answerIndex: 3},
    {q: "¿Cuál es la distancia oficial de un maratón?", options: ["42,195 km", "40 km", "45 km", "38,6 km"], answerIndex: 0},
    {q: "¿Sobre qué superficie se juega el torneo de Roland Garros?", options: ["Hierba", "Tierra batida", "Cemento", "Moqueta"], answerIndex: 1},
    {q: "¿Qué selección ganó el Mundial de fútbol de 2018?", options: ["Croacia", "Alemania", "Francia", "Bélgica"], answerIndex: 2},
    {q: "¿En qué deporte se entrega el Trofeo Vince Lombardi?", options: ["Baloncesto", "Béisbol", "Hockey sobre hielo", "Fútbol americano"], answerIndex: 3},
    {q: "¿Cuántos jugadores tiene en el agua un equipo de waterpolo?", options: ["Siete", "Seis", "Cinco", "Nueve"], answerIndex: 0},
    {q: "¿En qué país se originó el judo?", options: ["China", "Japón", "Corea", "Tailandia"], answerIndex: 1},
    {q: "¿Qué piloto alemán ganó siete campeonatos mundiales de Fórmula 1?", options: ["Sebastian Vettel", "Nico Rosberg", "Michael Schumacher", "Ralf Schumacher"], answerIndex: 2},
    {q: "¿Qué longitud tiene una piscina olímpica?", options: ["25 metros", "33 metros", "40 metros", "50 metros"], answerIndex: 3},
    {q: "¿En qué deporte se entrega el Balón de Oro?", options: ["Fútbol", "Baloncesto", "Balonmano", "Voleibol"], answerIndex: 0},
    {q: "¿Qué club inglés juega como local en Old Trafford?", options: ["Liverpool", "Manchester United", "Arsenal", "Chelsea"], answerIndex: 1},
    {q: "¿En cuántos cuartos se divide un partido de la NBA?", options: ["Dos", "Tres", "Cuatro", "Seis"], answerIndex: 2},
    {q: "¿Cuánto dura cada cuarto en un partido de la NBA?", options: ["8 minutos", "10 minutos", "15 minutos", "12 minutos"], answerIndex: 3},
    {q: "¿Qué disciplina olímpica combina esgrima, natación, equitación, tiro y carrera?", options: ["Pentatlón moderno", "Decatlón", "Triatlón", "Heptatlón"], answerIndex: 0},
    {q: "¿Qué ciclista belga es conocido como \"El Caníbal\"?", options: ["Bernard Hinault", "Eddy Merckx", "Jacques Anquetil", "Fausto Coppi"], answerIndex: 1},
    {q: "¿Qué selección de fútbol es conocida como \"La Albiceleste\"?", options: ["Uruguay", "Chile", "Argentina", "Perú"], answerIndex: 2},
    {q: "¿En qué deporte se lanza la jabalina?", options: ["Halterofilia", "Gimnasia", "Esgrima", "Atletismo"], answerIndex: 3},
    {q: "¿Cuántos jugadores tiene en la pista un equipo de hockey sobre hielo?", options: ["Seis", "Cinco", "Siete", "Ocho"], answerIndex: 0},
    {q: "¿Qué torneo de golf se disputa cada año en Augusta?", options: ["El Abierto Británico", "El Masters", "El US Open", "El PGA Championship"], answerIndex: 1},
    {q: "¿Qué país organizó los Juegos Olímpicos de Invierno de 2018?", options: ["Rusia", "Japón", "Corea del Sur", "Canadá"], answerIndex: 2},
    {q: "¿Qué boxeador mexicano es conocido como \"Canelo\"?", options: ["Julio César Chávez", "Juan Manuel Márquez", "Érik Morales", "Saúl Álvarez"], answerIndex: 3},
    {q: "¿En qué deporte se usa el término \"break point\"?", options: ["Tenis", "Golf", "Natación", "Ciclismo"], answerIndex: 0},
    {q: "¿Qué país es la sede del Tour de Francia?", options: ["Bélgica", "Francia", "Italia", "Suiza"], answerIndex: 1},
    {q: "¿Cuántos jugadores forman un equipo de balonmano en cancha?", options: ["Cinco", "Seis", "Siete", "Ocho"], answerIndex: 2},
  ],

  d3: [
    {q: "¿Qué atleta estadounidense ganó cuatro medallas de oro en los Juegos de Berlín 1936?", options: ["Jesse Owens", "Carl Lewis", "Ralph Metcalfe", "Eddie Tolan"], answerIndex: 0},
    {q: "¿Qué futbolista alemán ganó el Mundial como jugador y luego como entrenador?", options: ["Gerd Müller", "Franz Beckenbauer", "Lothar Matthäus", "Jürgen Klinsmann"], answerIndex: 1},
    {q: "¿Qué selección ganó el primer Campeonato Mundial de Baloncesto en 1950?", options: ["Estados Unidos", "Brasil", "Argentina", "Yugoslavia"], answerIndex: 2},
    {q: "¿Qué tenista completó el Golden Slam en 1988?", options: ["Martina Navratilova", "Chris Evert", "Monica Seles", "Steffi Graf"], answerIndex: 3},
    {q: "¿Qué escudería tiene más títulos de constructores en la Fórmula 1?", options: ["Ferrari", "McLaren", "Williams", "Mercedes"], answerIndex: 0},
    {q: "¿Qué ciclista español ganó cinco Tours de Francia consecutivos en los años 90?", options: ["Pedro Delgado", "Miguel Induráin", "Alberto Contador", "Óscar Freire"], answerIndex: 1},
    {q: "¿En qué ciudad se celebraron los primeros Juegos Paralímpicos oficiales, en 1960?", options: ["Londres", "Tokio", "Roma", "Heidelberg"], answerIndex: 2},
    {q: "¿Qué gimnasta rumana consiguió el primer 10 perfecto en unos Juegos Olímpicos?", options: ["Olga Kórbut", "Larisa Latýnina", "Vera Cáslavská", "Nadia Comăneci"], answerIndex: 3},
    {q: "¿Qué corredor checo ganó tres oros de fondo en los Juegos de Helsinki 1952?", options: ["Emil Zátopek", "Paavo Nurmi", "Vladimir Kuts", "Lasse Virén"], answerIndex: 0},
    {q: "¿Qué selección africana fue la primera en alcanzar los cuartos de final de un Mundial?", options: ["Nigeria", "Camerún", "Senegal", "Ghana"], answerIndex: 1},
    {q: "¿Qué jugador anotó 100 puntos en un solo partido de la NBA?", options: ["Kareem Abdul-Jabbar", "Elgin Baylor", "Wilt Chamberlain", "Bill Russell"], answerIndex: 2},
    {q: "¿Qué ajedrecista fue campeón mundial durante más de quince años desde 1985?", options: ["Anatoli Kárpov", "Vladímir Krámnik", "Bobby Fischer", "Garri Kaspárov"], answerIndex: 3},
    {q: "¿Qué país ha ganado más medallas en la historia de los Juegos Olímpicos de Invierno?", options: ["Noruega", "Estados Unidos", "Alemania", "Canadá"], answerIndex: 0},
    {q: "¿En qué deporte se disputa la Copa Davis?", options: ["Golf", "Tenis", "Rugby", "Vela"], answerIndex: 1},
    {q: "¿Qué piloto brasileño de Fórmula 1 falleció en el circuito de Imola en 1994?", options: ["Nelson Piquet", "Emerson Fittipaldi", "Ayrton Senna", "Rubens Barrichello"], answerIndex: 2},
    {q: "¿Qué club ganó la primera edición de la Copa de Europa en 1956?", options: ["Benfica", "Milan", "Ajax", "Real Madrid"], answerIndex: 3},
    {q: "¿Qué atleta etíope ganó descalzo el maratón olímpico de Roma 1960?", options: ["Abebe Bikila", "Haile Gebrselassie", "Kenenisa Bekele", "Mamo Wolde"], answerIndex: 0},
  ],
};
