module.exports = {
  d1: [
    {q: "¿Con qué parte del cuerpo no puede tocar el balón un jugador de campo en el fútbol?", options: ["El pecho", "La cabeza", "Las manos", "Los muslos"], answerIndex: 2},
    {q: "¿Cuántos tiempos tiene un partido de fútbol reglamentario?", options: ["Dos", "Uno", "Tres", "Cuatro"], answerIndex: 0},
    {q: "¿Cuántos minutos dura cada tiempo de un partido de fútbol?", options: ["45", "50", "40", "30"], answerIndex: 0},
    {q: "¿Qué deporte se juega con un balón naranja y un aro elevado?", options: ["Balonmano", "Baloncesto", "Voleibol", "Rugby"], answerIndex: 1},
    {q: "¿En qué deporte se usa un bate, una pelota y se corre entre bases?", options: ["Golf", "Críquet", "Béisbol", "Hockey"], answerIndex: 2},
    {q: "¿De qué color es la tarjeta con la que se expulsa a un jugador de fútbol?", options: ["Roja", "Azul", "Amarilla", "Verde"], answerIndex: 0},
    {q: "¿En qué deporte compiten Rafael Nadal y Roger Federer?", options: ["Pádel", "Bádminton", "Squash", "Tenis"], answerIndex: 3},
    {q: "¿Qué deporte se practica sobre hielo con un disco y bastones?", options: ["Hockey sobre hielo", "Patinaje artístico", "Curling", "Bobsleigh"], answerIndex: 0},
    {q: "¿En qué deporte se anota un \"home run\"?", options: ["Rugby", "Fútbol americano", "Béisbol", "Baloncesto"], answerIndex: 2},
    {q: "¿En qué país se disputa el torneo de tenis de Roland Garros?", options: ["Francia", "Estados Unidos", "Australia", "Reino Unido"], answerIndex: 0},
    {q: "¿Qué animal se monta en las competencias de equitación?", options: ["El elefante", "El toro", "El caballo", "El camello"], answerIndex: 2},
    {q: "¿Con qué se golpea la pelota en el golf?", options: ["Un mazo", "Un palo", "Una raqueta", "Un bate"], answerIndex: 1},
    {q: "¿Qué deporte se practica con un balón ovalado y cascos en Estados Unidos?", options: ["Lacrosse", "Balonmano", "Rugby", "Fútbol americano"], answerIndex: 3},
    {q: "¿Cuántas ruedas tiene una bicicleta de carreras?", options: ["Cuatro", "Dos", "Tres", "Una"], answerIndex: 1},
    {q: "¿Qué se necesita cruzar para ganar una carrera de atletismo?", options: ["La línea de meta", "La línea de salida", "El carril central", "La zona de relevos"], answerIndex: 0},
    {q: "¿En qué deporte destacó Michael Jordan?", options: ["Fútbol americano", "Baloncesto", "Béisbol", "Atletismo"], answerIndex: 1},
  ],

  d2: [
    {q: "¿En qué ciudad se celebraron los Juegos Olímpicos de 2020, aplazados a 2021?", options: ["Seúl", "París", "Tokio", "Pekín"], answerIndex: 2},
    {q: "¿Cuántos jugadores tiene en el campo un equipo de rugby union?", options: ["11", "13", "15", "9"], answerIndex: 2},
    {q: "¿Qué selección ganó la Eurocopa de 2021?", options: ["Inglaterra", "Francia", "Italia", "España"], answerIndex: 2},
    {q: "¿Qué club español ha ganado más Copas de Europa y Champions League?", options: ["Valencia", "Barcelona", "Atlético de Madrid", "Real Madrid"], answerIndex: 3},
    {q: "¿Cuál es la distancia oficial de un maratón?", options: ["38,6 km", "40 km", "45 km", "42,195 km"], answerIndex: 3},
    {q: "¿Sobre qué superficie se juega el torneo de Roland Garros?", options: ["Moqueta", "Tierra batida", "Hierba", "Cemento"], answerIndex: 1},
    {q: "¿Qué selección ganó el Mundial de fútbol de 2018?", options: ["Francia", "Croacia", "Alemania", "Bélgica"], answerIndex: 0},
    {q: "¿En qué deporte se entrega el Trofeo Vince Lombardi?", options: ["Baloncesto", "Fútbol americano", "Béisbol", "Hockey sobre hielo"], answerIndex: 1},
    {q: "¿Cuántos jugadores tiene en el agua un equipo de waterpolo?", options: ["Cinco", "Siete", "Nueve", "Seis"], answerIndex: 1},
    {q: "¿En qué país se originó el judo?", options: ["Corea", "Tailandia", "China", "Japón"], answerIndex: 3},
    {q: "¿Qué piloto alemán ganó siete campeonatos mundiales de Fórmula 1?", options: ["Sebastian Vettel", "Ralf Schumacher", "Michael Schumacher", "Nico Rosberg"], answerIndex: 2},
    {q: "¿Qué longitud tiene una piscina olímpica?", options: ["33 metros", "50 metros", "40 metros", "25 metros"], answerIndex: 1},
    {q: "¿En qué deporte se entrega el Balón de Oro?", options: ["Fútbol", "Baloncesto", "Balonmano", "Voleibol"], answerIndex: 0},
    {q: "¿Qué club inglés juega como local en Old Trafford?", options: ["Chelsea", "Manchester United", "Liverpool", "Arsenal"], answerIndex: 1},
    {q: "¿En cuántos cuartos se divide un partido de la NBA?", options: ["Cuatro", "Tres", "Dos", "Seis"], answerIndex: 0},
    {q: "¿Cuánto dura cada cuarto en un partido de la NBA?", options: ["15 minutos", "10 minutos", "12 minutos", "8 minutos"], answerIndex: 2},
    {q: "¿Qué disciplina olímpica combina esgrima, natación, equitación, tiro y carrera?", options: ["Decatlón", "Heptatlón", "Pentatlón moderno", "Triatlón"], answerIndex: 2},
    {q: "¿Qué ciclista belga es conocido como \"El Caníbal\"?", options: ["Eddy Merckx", "Fausto Coppi", "Bernard Hinault", "Jacques Anquetil"], answerIndex: 0},
    {q: "¿Qué selección de fútbol es conocida como \"La Albiceleste\"?", options: ["Chile", "Perú", "Argentina", "Uruguay"], answerIndex: 2},
    {q: "¿En qué deporte se lanza la jabalina?", options: ["Esgrima", "Halterofilia", "Atletismo", "Gimnasia"], answerIndex: 2},
    {q: "¿Cuántos jugadores tiene en la pista un equipo de hockey sobre hielo?", options: ["Siete", "Seis", "Ocho", "Cinco"], answerIndex: 1},
    {q: "¿Qué torneo de golf se disputa cada año en Augusta?", options: ["El Abierto Británico", "El US Open", "El PGA Championship", "El Masters"], answerIndex: 3},
    {q: "¿Qué país organizó los Juegos Olímpicos de Invierno de 2018?", options: ["Japón", "Canadá", "Corea del Sur", "Rusia"], answerIndex: 2},
    {q: "¿Qué boxeador mexicano es conocido como \"Canelo\"?", options: ["Saúl Álvarez", "Juan Manuel Márquez", "Julio César Chávez", "Érik Morales"], answerIndex: 0},
    {q: "¿En qué deporte se usa el término \"break point\"?", options: ["Tenis", "Natación", "Golf", "Ciclismo"], answerIndex: 0},
    {q: "¿Qué país es la sede del Tour de Francia?", options: ["Bélgica", "Italia", "Francia", "Suiza"], answerIndex: 2},
    {q: "¿Cuántos jugadores forman un equipo de balonmano en cancha?", options: ["Siete", "Cinco", "Seis", "Ocho"], answerIndex: 0},
  ],

  d3: [
    {q: "¿Qué atleta estadounidense ganó cuatro medallas de oro en los Juegos de Berlín 1936?", options: ["Ralph Metcalfe", "Eddie Tolan", "Jesse Owens", "Carl Lewis"], answerIndex: 2},
    {q: "¿Qué futbolista alemán ganó el Mundial como jugador y luego como entrenador?", options: ["Jürgen Klinsmann", "Gerd Müller", "Lothar Matthäus", "Franz Beckenbauer"], answerIndex: 3},
    {q: "¿Qué selección ganó el primer Campeonato Mundial de Baloncesto en 1950?", options: ["Yugoslavia", "Brasil", "Estados Unidos", "Argentina"], answerIndex: 3},
    {q: "¿Qué tenista completó el Golden Slam en 1988?", options: ["Chris Evert", "Martina Navratilova", "Monica Seles", "Steffi Graf"], answerIndex: 3},
    {q: "¿Qué escudería tiene más títulos de constructores en la Fórmula 1?", options: ["McLaren", "Mercedes", "Williams", "Ferrari"], answerIndex: 3},
    {q: "¿Qué ciclista español ganó cinco Tours de Francia consecutivos en los años 90?", options: ["Alberto Contador", "Miguel Induráin", "Pedro Delgado", "Óscar Freire"], answerIndex: 1},
    {q: "¿En qué ciudad se celebraron los primeros Juegos Paralímpicos oficiales, en 1960?", options: ["Tokio", "Roma", "Heidelberg", "Londres"], answerIndex: 1},
    {q: "¿Qué gimnasta rumana consiguió el primer 10 perfecto en unos Juegos Olímpicos?", options: ["Larisa Latýnina", "Olga Kórbut", "Vera Cáslavská", "Nadia Comăneci"], answerIndex: 3},
    {q: "¿Qué corredor checo ganó tres oros de fondo en los Juegos de Helsinki 1952?", options: ["Paavo Nurmi", "Lasse Virén", "Vladimir Kuts", "Emil Zátopek"], answerIndex: 3},
    {q: "¿Qué selección africana fue la primera en alcanzar los cuartos de final de un Mundial?", options: ["Nigeria", "Ghana", "Camerún", "Senegal"], answerIndex: 2},
    {q: "¿Qué jugador anotó 100 puntos en un solo partido de la NBA?", options: ["Bill Russell", "Wilt Chamberlain", "Kareem Abdul-Jabbar", "Elgin Baylor"], answerIndex: 1},
    {q: "¿Qué ajedrecista fue campeón mundial durante más de quince años desde 1985?", options: ["Garri Kaspárov", "Bobby Fischer", "Vladímir Krámnik", "Anatoli Kárpov"], answerIndex: 0},
    {q: "¿Qué país ha ganado más medallas en la historia de los Juegos Olímpicos de Invierno?", options: ["Estados Unidos", "Canadá", "Alemania", "Noruega"], answerIndex: 3},
    {q: "¿En qué deporte se disputa la Copa Davis?", options: ["Rugby", "Golf", "Vela", "Tenis"], answerIndex: 3},
    {q: "¿Qué piloto brasileño de Fórmula 1 falleció en el circuito de Imola en 1994?", options: ["Nelson Piquet", "Rubens Barrichello", "Emerson Fittipaldi", "Ayrton Senna"], answerIndex: 3},
    {q: "¿Qué club ganó la primera edición de la Copa de Europa en 1956?", options: ["Benfica", "Ajax", "Real Madrid", "Milan"], answerIndex: 2},
    {q: "¿Qué atleta etíope ganó descalzo el maratón olímpico de Roma 1960?", options: ["Abebe Bikila", "Kenenisa Bekele", "Mamo Wolde", "Haile Gebrselassie"], answerIndex: 0},
  ],
};
