module.exports = {
  d1: [
    {q: "¿Cuál es la capital de Italia?", options: ["Roma", "Milán", "Nápoles", "Turín"], answerIndex: 0},
    {q: "¿Cuál es la capital de Alemania?", options: ["Múnich", "Berlín", "Hamburgo", "Fráncfort"], answerIndex: 1},
    {q: "¿En qué continente se encuentra Australia?", options: ["Asia", "África", "Oceanía", "América"], answerIndex: 2},
    {q: "¿Qué país es famoso por la Torre Eiffel?", options: ["Italia", "Bélgica", "Suiza", "Francia"], answerIndex: 3},
    {q: "¿Cuál es la capital de Argentina?", options: ["Buenos Aires", "Córdoba", "Rosario", "Mendoza"], answerIndex: 0},
    {q: "¿En qué país se encuentra la Gran Muralla?", options: ["Japón", "China", "India", "Mongolia"], answerIndex: 1},
    {q: "¿Cuál es el continente más frío del planeta?", options: ["Europa", "América del Norte", "Antártida", "Asia"], answerIndex: 2},
    {q: "¿Cuál es la capital de Perú?", options: ["Cusco", "Arequipa", "Trujillo", "Lima"], answerIndex: 3},
    {q: "¿Qué mar separa Europa de África?", options: ["El Mediterráneo", "El Báltico", "El Caribe", "El Negro"], answerIndex: 0},
    {q: "¿Cuál es la capital de Colombia?", options: ["Medellín", "Bogotá", "Cali", "Cartagena"], answerIndex: 1},
    {q: "¿Qué línea imaginaria divide la Tierra en hemisferio norte y sur?", options: ["El meridiano de Greenwich", "El trópico de Cáncer", "El ecuador", "El círculo polar"], answerIndex: 2},
    {q: "¿Cuál es la capital de Chile?", options: ["Valparaíso", "Concepción", "Antofagasta", "Santiago"], answerIndex: 3},
    {q: "¿En qué continente se encuentra Brasil?", options: ["América del Sur", "América Central", "África", "Oceanía"], answerIndex: 0},
    {q: "¿Qué océano baña la costa este de Estados Unidos?", options: ["El Pacífico", "El Atlántico", "El Índico", "El Ártico"], answerIndex: 1},
    {q: "¿Cuál es la capital de Portugal?", options: ["Oporto", "Braga", "Lisboa", "Coímbra"], answerIndex: 2},
    {q: "¿Qué país sudamericano es largo y estrecho a lo largo de la costa del Pacífico?", options: ["Perú", "Ecuador", "Colombia", "Chile"], answerIndex: 3},
  ],

  d2: [
    {q: "¿Cuál es la capital de Nueva Zelanda?", options: ["Wellington", "Auckland", "Christchurch", "Dunedin"], answerIndex: 0},
    {q: "¿Cuál es el segundo país más grande del mundo por superficie?", options: ["China", "Canadá", "Estados Unidos", "Brasil"], answerIndex: 1},
    {q: "¿Qué desierto se extiende por Mongolia y el norte de China?", options: ["El Karakum", "El Taklamakán", "El Gobi", "El Kizilkum"], answerIndex: 2},
    {q: "¿Cuál es el país más poblado de África?", options: ["Egipto", "Etiopía", "Sudáfrica", "Nigeria"], answerIndex: 3},
    {q: "¿Qué cordillera marca tradicionalmente la separación entre Europa y Asia?", options: ["Los Urales", "El Cáucaso", "Los Cárpatos", "Los Balcanes"], answerIndex: 0},
    {q: "¿Cuál es la capital de Turquía?", options: ["Estambul", "Ankara", "Esmirna", "Bursa"], answerIndex: 1},
    {q: "¿Qué canal artificial conecta el Atlántico con el Pacífico en América Central?", options: ["El canal de Suez", "El canal de Kiel", "El canal de Panamá", "El canal de Corinto"], answerIndex: 2},
    {q: "¿Qué canal conecta el mar Mediterráneo con el mar Rojo?", options: ["El canal de Panamá", "El canal de Kiel", "El canal de Corinto", "El canal de Suez"], answerIndex: 3},
    {q: "¿Cuál es el lago más profundo del mundo?", options: ["El lago Baikal", "El lago Tanganica", "El lago Superior", "El mar Caspio"], answerIndex: 0},
    {q: "¿Cuál es la capital de Egipto?", options: ["Alejandría", "El Cairo", "Guiza", "Luxor"], answerIndex: 1},
    {q: "¿Cuál es la isla más grande del mundo?", options: ["Nueva Guinea", "Borneo", "Groenlandia", "Madagascar"], answerIndex: 2},
    {q: "¿Cuál es la capital de Etiopía?", options: ["Jartum", "Nairobi", "Mogadiscio", "Adís Abeba"], answerIndex: 3},
    {q: "¿Cuál es la capital de Rusia?", options: ["Moscú", "San Petersburgo", "Novosibirsk", "Kazán"], answerIndex: 0},
    {q: "¿Qué país sudamericano no tiene salida al mar junto con Paraguay?", options: ["Ecuador", "Bolivia", "Uruguay", "Venezuela"], answerIndex: 1},
    {q: "¿Cuál es el río más largo de Europa?", options: ["El Danubio", "El Rin", "El Volga", "El Dniéper"], answerIndex: 2},
    {q: "¿Qué estrecho separa Alaska de Rusia?", options: ["El estrecho de Ormuz", "El estrecho de Malaca", "El estrecho de Magallanes", "El estrecho de Bering"], answerIndex: 3},
    {q: "¿Cuál es la capital de Marruecos?", options: ["Rabat", "Casablanca", "Marrakech", "Fez"], answerIndex: 0},
    {q: "¿Cuál es la montaña más alta de África?", options: ["El monte Kenia", "El Kilimanjaro", "El monte Stanley", "El Toubkal"], answerIndex: 1},
    {q: "¿Cuál es la capital de Kenia?", options: ["Kampala", "Dar es Salaam", "Nairobi", "Lusaka"], answerIndex: 2},
    {q: "¿Cuál es el país más poblado de la Unión Europea?", options: ["Francia", "Italia", "España", "Alemania"], answerIndex: 3},
    {q: "¿Qué océano baña la costa oeste de América del Sur?", options: ["El Pacífico", "El Atlántico", "El Índico", "El Ártico"], answerIndex: 0},
    {q: "¿Qué desierto sudamericano es considerado el lugar más árido del mundo?", options: ["El Patagónico", "El de Atacama", "El de Sechura", "El de La Guajira"], answerIndex: 1},
    {q: "¿Cuál es la capital de la India?", options: ["Bombay", "Calcuta", "Nueva Delhi", "Bangalore"], answerIndex: 2},
    {q: "¿Qué país europeo es famoso por sus tulipanes y molinos de viento?", options: ["Bélgica", "Dinamarca", "Suiza", "Países Bajos"], answerIndex: 3},
    {q: "¿Qué país tiene el mayor número de volcanes activos?", options: ["Indonesia", "Japón", "Chile", "Islandia"], answerIndex: 0},
    {q: "¿Cuál es el mar que baña las costas de Grecia y el oeste de Turquía?", options: ["El mar Negro", "El mar Egeo", "El mar Jónico", "El mar Adriático"], answerIndex: 1},
    {q: "¿Qué país africano tiene como capital Pretoria en su función administrativa?", options: ["Namibia", "Zimbabue", "Sudáfrica", "Botsuana"], answerIndex: 2},
  ],

  d3: [
    {q: "¿Cuál es la capital de Bután?", options: ["Timbu", "Katmandú", "Daca", "Timor"], answerIndex: 0},
    {q: "¿Cuál es el país soberano más densamente poblado del mundo?", options: ["Singapur", "Mónaco", "Malta", "Bangladés"], answerIndex: 1},
    {q: "¿Qué río forma buena parte de la frontera entre México y Estados Unidos?", options: ["El Colorado", "El Misisipi", "El Río Bravo", "El Usumacinta"], answerIndex: 2},
    {q: "¿Cuál es la capital de Myanmar desde 2006?", options: ["Rangún", "Mandalay", "Bago", "Naipyidó"], answerIndex: 3},
    {q: "¿Qué desierto costero de Namibia es considerado el más antiguo del mundo?", options: ["El Namib", "El Kalahari", "El Danakil", "El Karoo"], answerIndex: 0},
    {q: "¿Qué país africano fue fundado por personas esclavizadas liberadas de Estados Unidos?", options: ["Sierra Leona", "Liberia", "Ghana", "Costa de Marfil"], answerIndex: 1},
    {q: "¿Cuál es la montaña más alta de Australia continental?", options: ["El monte Ossa", "El monte Bogong", "El monte Kosciuszko", "El monte Zeil"], answerIndex: 2},
    {q: "¿Qué estrecho separa Sicilia de la península itálica?", options: ["El de Otranto", "El de Bonifacio", "El de Gibraltar", "El de Mesina"], answerIndex: 3},
    {q: "¿Cuál es la capital de Uzbekistán?", options: ["Taskent", "Samarcanda", "Bujará", "Nukus"], answerIndex: 0},
    {q: "¿Qué país tiene la única bandera nacional que no es rectangular?", options: ["Suiza", "Nepal", "Vaticano", "Catar"], answerIndex: 1},
    {q: "¿Qué mar del Atlántico no tiene costas y está delimitado por corrientes marinas?", options: ["El mar de Weddell", "El mar de Coral", "El mar de los Sargazos", "El mar de Labrador"], answerIndex: 2},
    {q: "¿Cuál es la capital constitucional de Bolivia?", options: ["La Paz", "Santa Cruz", "Cochabamba", "Sucre"], answerIndex: 3},
    {q: "¿Qué cordillera atraviesa Marruecos, Argelia y Túnez?", options: ["El Atlas", "El Rif", "El Ahaggar", "El Tibesti"], answerIndex: 0},
    {q: "¿Cuál es el país más joven reconocido por la ONU?", options: ["Timor Oriental", "Sudán del Sur", "Montenegro", "Kosovo"], answerIndex: 1},
    {q: "¿Cuál es el lago de agua dulce más grande de África por superficie?", options: ["El lago Chad", "El lago Tanganica", "El lago Victoria", "El lago Malaui"], answerIndex: 2},
    {q: "¿Qué corriente oceánica cálida suaviza el clima del noroeste de Europa?", options: ["La corriente de Humboldt", "La corriente de Canarias", "La corriente de Benguela", "La corriente del Golfo"], answerIndex: 3},
    {q: "¿Qué archipiélago noruego se sitúa entre el continente y el océano Ártico?", options: ["Svalbard", "Lofoten", "Feroe", "Åland"], answerIndex: 0},
  ],
};
