module.exports = {
  d1: [
    {q: "¿Cuál es la capital de Italia?", options: ["Milán", "Roma", "Nápoles", "Turín"], answerIndex: 1},
    {q: "¿Cuál es la capital de Alemania?", options: ["Hamburgo", "Fráncfort", "Múnich", "Berlín"], answerIndex: 3},
    {q: "¿En qué continente se encuentra Australia?", options: ["Oceanía", "América", "África", "Asia"], answerIndex: 0},
    {q: "¿Qué país es famoso por la Torre Eiffel?", options: ["Suiza", "Francia", "Bélgica", "Italia"], answerIndex: 1},
    {q: "¿Cuál es la capital de Argentina?", options: ["Mendoza", "Córdoba", "Buenos Aires", "Rosario"], answerIndex: 2},
    {q: "¿En qué país se encuentra la Gran Muralla?", options: ["China", "Mongolia", "Japón", "India"], answerIndex: 0},
    {q: "¿Cuál es el continente más frío del planeta?", options: ["Europa", "Asia", "América del Norte", "Antártida"], answerIndex: 3},
    {q: "¿Cuál es la capital de Perú?", options: ["Cusco", "Lima", "Trujillo", "Arequipa"], answerIndex: 1},
    {q: "¿Qué mar separa Europa de África?", options: ["El Caribe", "El Negro", "El Báltico", "El Mediterráneo"], answerIndex: 3},
    {q: "¿Cuál es la capital de Colombia?", options: ["Cartagena", "Cali", "Medellín", "Bogotá"], answerIndex: 3},
    {q: "¿Qué línea imaginaria divide la Tierra en hemisferio norte y sur?", options: ["El meridiano de Greenwich", "El círculo polar", "El ecuador", "El trópico de Cáncer"], answerIndex: 2},
    {q: "¿Cuál es la capital de Chile?", options: ["Valparaíso", "Concepción", "Santiago", "Antofagasta"], answerIndex: 2},
    {q: "¿En qué continente se encuentra Brasil?", options: ["África", "Oceanía", "América Central", "América del Sur"], answerIndex: 3},
    {q: "¿Qué océano baña la costa este de Estados Unidos?", options: ["El Atlántico", "El Ártico", "El Índico", "El Pacífico"], answerIndex: 0},
    {q: "¿Cuál es la capital de Portugal?", options: ["Oporto", "Braga", "Coímbra", "Lisboa"], answerIndex: 3},
    {q: "¿Qué país sudamericano es largo y estrecho a lo largo de la costa del Pacífico?", options: ["Perú", "Colombia", "Ecuador", "Chile"], answerIndex: 3},
  ],

  d2: [
    {q: "¿Cuál es la capital de Nueva Zelanda?", options: ["Christchurch", "Dunedin", "Wellington", "Auckland"], answerIndex: 2},
    {q: "¿Cuál es el segundo país más grande del mundo por superficie?", options: ["Estados Unidos", "Canadá", "Brasil", "China"], answerIndex: 1},
    {q: "¿Qué desierto se extiende por Mongolia y el norte de China?", options: ["El Karakum", "El Kizilkum", "El Gobi", "El Taklamakán"], answerIndex: 2},
    {q: "¿Cuál es el país más poblado de África?", options: ["Etiopía", "Egipto", "Nigeria", "Sudáfrica"], answerIndex: 2},
    {q: "¿Qué cordillera marca tradicionalmente la separación entre Europa y Asia?", options: ["Los Balcanes", "El Cáucaso", "Los Cárpatos", "Los Urales"], answerIndex: 3},
    {q: "¿Cuál es la capital de Turquía?", options: ["Bursa", "Ankara", "Estambul", "Esmirna"], answerIndex: 1},
    {q: "¿Qué canal artificial conecta el Atlántico con el Pacífico en América Central?", options: ["El canal de Suez", "El canal de Panamá", "El canal de Corinto", "El canal de Kiel"], answerIndex: 1},
    {q: "¿Qué canal conecta el mar Mediterráneo con el mar Rojo?", options: ["El canal de Kiel", "El canal de Panamá", "El canal de Corinto", "El canal de Suez"], answerIndex: 3},
    {q: "¿Cuál es el lago más profundo del mundo?", options: ["El lago Superior", "El lago Baikal", "El lago Tanganica", "El mar Caspio"], answerIndex: 1},
    {q: "¿Cuál es la capital de Egipto?", options: ["Luxor", "Alejandría", "El Cairo", "Guiza"], answerIndex: 2},
    {q: "¿Cuál es la isla más grande del mundo?", options: ["Groenlandia", "Madagascar", "Nueva Guinea", "Borneo"], answerIndex: 0},
    {q: "¿Cuál es la capital de Etiopía?", options: ["Jartum", "Mogadiscio", "Adís Abeba", "Nairobi"], answerIndex: 2},
    {q: "¿Cuál es la capital de Rusia?", options: ["San Petersburgo", "Kazán", "Moscú", "Novosibirsk"], answerIndex: 2},
    {q: "¿Qué país sudamericano no tiene salida al mar junto con Paraguay?", options: ["Venezuela", "Bolivia", "Uruguay", "Ecuador"], answerIndex: 1},
    {q: "¿Cuál es el río más largo de Europa?", options: ["El Volga", "El Dniéper", "El Danubio", "El Rin"], answerIndex: 0},
    {q: "¿Qué estrecho separa Alaska de Rusia?", options: ["El estrecho de Ormuz", "El estrecho de Malaca", "El estrecho de Bering", "El estrecho de Magallanes"], answerIndex: 2},
    {q: "¿Cuál es la capital de Marruecos?", options: ["Fez", "Rabat", "Marrakech", "Casablanca"], answerIndex: 1},
    {q: "¿Cuál es la montaña más alta de África?", options: ["El Toubkal", "El monte Stanley", "El monte Kenia", "El Kilimanjaro"], answerIndex: 3},
    {q: "¿Cuál es la capital de Kenia?", options: ["Dar es Salaam", "Lusaka", "Nairobi", "Kampala"], answerIndex: 2},
    {q: "¿Cuál es el país más poblado de la Unión Europea?", options: ["Alemania", "Francia", "Italia", "España"], answerIndex: 0},
    {q: "¿Qué océano baña la costa oeste de América del Sur?", options: ["El Pacífico", "El Ártico", "El Atlántico", "El Índico"], answerIndex: 0},
    {q: "¿Qué desierto sudamericano es considerado el lugar más árido del mundo?", options: ["El de Sechura", "El Patagónico", "El de Atacama", "El de La Guajira"], answerIndex: 2},
    {q: "¿Cuál es la capital de la India?", options: ["Nueva Delhi", "Bombay", "Bangalore", "Calcuta"], answerIndex: 0},
    {q: "¿Qué país europeo es famoso por sus tulipanes y molinos de viento?", options: ["Dinamarca", "Bélgica", "Países Bajos", "Suiza"], answerIndex: 2},
    {q: "¿Qué país tiene el mayor número de volcanes activos?", options: ["Indonesia", "Chile", "Islandia", "Japón"], answerIndex: 0},
    {q: "¿Cuál es el mar que baña las costas de Grecia y el oeste de Turquía?", options: ["El mar Jónico", "El mar Adriático", "El mar Egeo", "El mar Negro"], answerIndex: 2},
    {q: "¿Qué país africano tiene como capital Pretoria en su función administrativa?", options: ["Namibia", "Botsuana", "Zimbabue", "Sudáfrica"], answerIndex: 3},
  ],

  d3: [
    {q: "¿Cuál es la capital de Bután?", options: ["Katmandú", "Timbu", "Timor", "Daca"], answerIndex: 1},
    {q: "¿Cuál es el país soberano más densamente poblado del mundo?", options: ["Malta", "Mónaco", "Singapur", "Bangladés"], answerIndex: 1},
    {q: "¿Qué río forma buena parte de la frontera entre México y Estados Unidos?", options: ["El Misisipi", "El Río Bravo", "El Usumacinta", "El Colorado"], answerIndex: 1},
    {q: "¿Cuál es la capital de Myanmar desde 2006?", options: ["Rangún", "Naipyidó", "Bago", "Mandalay"], answerIndex: 1},
    {q: "¿Qué desierto costero de Namibia es considerado el más antiguo del mundo?", options: ["El Namib", "El Karoo", "El Danakil", "El Kalahari"], answerIndex: 0},
    {q: "¿Qué país africano fue fundado por personas esclavizadas liberadas de Estados Unidos?", options: ["Ghana", "Liberia", "Sierra Leona", "Costa de Marfil"], answerIndex: 1},
    {q: "¿Cuál es la montaña más alta de Australia continental?", options: ["El monte Kosciuszko", "El monte Ossa", "El monte Zeil", "El monte Bogong"], answerIndex: 0},
    {q: "¿Qué estrecho separa Sicilia de la península itálica?", options: ["El de Otranto", "El de Gibraltar", "El de Bonifacio", "El de Mesina"], answerIndex: 3},
    {q: "¿Cuál es la capital de Uzbekistán?", options: ["Samarcanda", "Nukus", "Taskent", "Bujará"], answerIndex: 2},
    {q: "¿Qué país tiene la única bandera nacional que no es rectangular?", options: ["Catar", "Vaticano", "Suiza", "Nepal"], answerIndex: 3},
    {q: "¿Qué mar del Atlántico no tiene costas y está delimitado por corrientes marinas?", options: ["El mar de Labrador", "El mar de Weddell", "El mar de Coral", "El mar de los Sargazos"], answerIndex: 3},
    {q: "¿Cuál es la capital constitucional de Bolivia?", options: ["Sucre", "La Paz", "Cochabamba", "Santa Cruz"], answerIndex: 0},
    {q: "¿Qué cordillera atraviesa Marruecos, Argelia y Túnez?", options: ["El Tibesti", "El Rif", "El Atlas", "El Ahaggar"], answerIndex: 2},
    {q: "¿Cuál es el país más joven reconocido por la ONU?", options: ["Montenegro", "Timor Oriental", "Sudán del Sur", "Kosovo"], answerIndex: 2},
    {q: "¿Cuál es el lago de agua dulce más grande de África por superficie?", options: ["El lago Chad", "El lago Victoria", "El lago Tanganica", "El lago Malaui"], answerIndex: 1},
    {q: "¿Qué corriente oceánica cálida suaviza el clima del noroeste de Europa?", options: ["La corriente de Canarias", "La corriente del Golfo", "La corriente de Humboldt", "La corriente de Benguela"], answerIndex: 1},
    {q: "¿Qué archipiélago noruego se sitúa entre el continente y el océano Ártico?", options: ["Åland", "Lofoten", "Svalbard", "Feroe"], answerIndex: 2},
  ],
};
