module.exports = {
  d1: [
    {q: "¿En qué año llegó el ser humano a la Luna por primera vez?", options: ["1969", "1959", "1975", "1981"], answerIndex: 0},
    {q: "¿Qué civilización antigua construyó las pirámides de Guiza?", options: ["La griega", "La egipcia", "La persa", "La fenicia"], answerIndex: 1},
    {q: "¿Quién lideró la Alemania nazi durante la Segunda Guerra Mundial?", options: ["Heinrich Himmler", "Hermann Göring", "Adolf Hitler", "Joseph Goebbels"], answerIndex: 2},
    {q: "¿Qué barco se hundió en 1912 tras chocar contra un iceberg?", options: ["El Lusitania", "El Britannic", "El Bismarck", "El Titanic"], answerIndex: 3},
    {q: "¿Qué civilización antigua creó los Juegos Olímpicos?", options: ["La griega", "La romana", "La egipcia", "La china"], answerIndex: 0},
    {q: "¿En qué país se construyó el Taj Mahal?", options: ["Pakistán", "India", "Irán", "Turquía"], answerIndex: 1},
    {q: "¿Qué antigua ciudad romana quedó sepultada por la erupción del Vesubio?", options: ["Ostia", "Cartago", "Pompeya", "Éfeso"], answerIndex: 2},
    {q: "¿Quién fue la primera mujer en recibir un Premio Nobel?", options: ["Rosalind Franklin", "Ada Lovelace", "Lise Meitner", "Marie Curie"], answerIndex: 3},
    {q: "¿Qué invento de Johannes Gutenberg revolucionó la difusión del conocimiento?", options: ["La imprenta", "El telescopio", "La brújula", "El papel"], answerIndex: 0},
    {q: "¿En qué continente aparecieron los primeros seres humanos según la evidencia científica?", options: ["Asia", "África", "Europa", "Oceanía"], answerIndex: 1},
    {q: "¿Qué rey inglés del siglo XVI tuvo seis esposas?", options: ["Ricardo III", "Eduardo VI", "Enrique VIII", "Jacobo I"], answerIndex: 2},
    {q: "¿Qué gran conflicto mundial ocurrió entre 1914 y 1918?", options: ["La Guerra de Corea", "La Guerra Fría", "La Segunda Guerra Mundial", "La Primera Guerra Mundial"], answerIndex: 3},
    {q: "¿Quién pronunció el discurso \"I have a dream\" en 1963?", options: ["Martin Luther King", "Malcolm X", "Rosa Parks", "Nelson Mandela"], answerIndex: 0},
    {q: "¿Qué barco llevó a los peregrinos ingleses a América en 1620?", options: ["El Santa María", "El Mayflower", "El Beagle", "El Victoria"], answerIndex: 1},
    {q: "¿Qué imperio antiguo era gobernado por los faraones?", options: ["El persa", "El babilónico", "El egipcio", "El asirio"], answerIndex: 2},
    {q: "¿Qué material dio nombre a la Edad de Bronce?", options: ["El hierro", "La piedra", "El oro", "El bronce"], answerIndex: 3},
  ],

  d2: [
    {q: "¿Qué revolución comenzó con la toma de la Bastilla en 1789?", options: ["La Revolución Francesa", "La Revolución Rusa", "La Revolución Industrial", "La Revolución Americana"], answerIndex: 0},
    {q: "¿Quién fue el primer emperador de Roma?", options: ["Julio César", "Augusto", "Tiberio", "Nerón"], answerIndex: 1},
    {q: "¿Qué general cartaginés cruzó los Alpes con elefantes para atacar Roma?", options: ["Amílcar Barca", "Asdrúbal", "Aníbal", "Escipión"], answerIndex: 2},
    {q: "¿Qué tratado firmado en 1957 creó la Comunidad Económica Europea?", options: ["El Tratado de Maastricht", "El Tratado de París", "El Tratado de Lisboa", "El Tratado de Roma"], answerIndex: 3},
    {q: "¿Qué rey de Macedonia conquistó el Imperio persa?", options: ["Alejandro Magno", "Filipo II", "Ptolomeo I", "Seleuco"], answerIndex: 0},
    {q: "¿Qué civilización de Mesopotamia desarrolló la escritura cuneiforme?", options: ["Los hititas", "Los sumerios", "Los medos", "Los arameos"], answerIndex: 1},
    {q: "¿Quién fue el primer ser humano en viajar al espacio?", options: ["Alan Shepard", "Neil Armstrong", "Yuri Gagarin", "Valentina Tereshkova"], answerIndex: 2},
    {q: "¿En qué año comenzó la Primera Guerra Mundial?", options: ["1912", "1918", "1920", "1914"], answerIndex: 3},
    {q: "¿Qué nombre recibe el enfrentamiento entre Estados Unidos y la URSS sin combate directo?", options: ["La Guerra Fría", "La Guerra de Corea", "La Guerra del Golfo", "La Guerra de Vietnam"], answerIndex: 0},
    {q: "¿Qué presidente estadounidense impulsó la abolición de la esclavitud?", options: ["Andrew Jackson", "Abraham Lincoln", "Thomas Jefferson", "Ulysses Grant"], answerIndex: 1},
    {q: "¿Qué expedición completó la primera vuelta al mundo?", options: ["La de Vasco da Gama", "La de Américo Vespucio", "La de Magallanes y Elcano", "La de Francis Drake"], answerIndex: 2},
    {q: "¿Qué epidemia devastó Europa a mediados del siglo XIV?", options: ["La gripe española", "El cólera", "La viruela", "La peste negra"], answerIndex: 3},
    {q: "¿Qué líder sudafricano pasó 27 años en prisión antes de ser presidente?", options: ["Nelson Mandela", "Desmond Tutu", "Steve Biko", "Thabo Mbeki"], answerIndex: 0},
    {q: "¿Qué civilización mesoamericana construyó ciudades como Tikal y Palenque?", options: ["La olmeca", "La maya", "La tolteca", "La zapoteca"], answerIndex: 1},
    {q: "¿Qué guerra enfrentó a Atenas y Esparta en la antigua Grecia?", options: ["Las Guerras Médicas", "La Guerra de Troya", "La Guerra del Peloponeso", "Las Guerras Púnicas"], answerIndex: 2},
    {q: "¿En qué año se fundó la Organización de las Naciones Unidas?", options: ["1919", "1939", "1950", "1945"], answerIndex: 3},
    {q: "¿Qué revolución de 1959 llevó a Fidel Castro al poder?", options: ["La Revolución cubana", "La Revolución mexicana", "La Revolución sandinista", "La Revolución boliviana"], answerIndex: 0},
    {q: "¿Qué muro defensivo construyeron los romanos en el norte de Britania?", options: ["El limes germánico", "El muro de Adriano", "La muralla Aureliana", "El muro de Antonino Pío"], answerIndex: 1},
    {q: "¿Qué documento inglés de 1215 limitó el poder del monarca?", options: ["La Petición de Derechos", "El Bill of Rights", "La Carta Magna", "El Acta de Unión"], answerIndex: 2},
    {q: "¿Quién lideró la independencia de Venezuela, Colombia, Ecuador y Bolivia?", options: ["José de San Martín", "Antonio José de Sucre", "Francisco de Miranda", "Simón Bolívar"], answerIndex: 3},
    {q: "¿Qué país lanzó el Sputnik, el primer satélite artificial?", options: ["La Unión Soviética", "Estados Unidos", "Alemania", "Reino Unido"], answerIndex: 0},
    {q: "¿Qué imperio africano medieval fue célebre por su oro y por Mansa Musa?", options: ["Songhay", "Malí", "Ghana", "Kanem-Bornu"], answerIndex: 1},
    {q: "¿En qué año terminó la Primera Guerra Mundial?", options: ["1916", "1917", "1918", "1919"], answerIndex: 2},
    {q: "¿Sobre qué ciudad japonesa se lanzó la primera bomba atómica?", options: ["Tokio", "Nagasaki", "Kioto", "Hiroshima"], answerIndex: 3},
    {q: "¿Qué explorador noruego alcanzó primero el Polo Sur?", options: ["Roald Amundsen", "Robert Falcon Scott", "Ernest Shackleton", "Fridtjof Nansen"], answerIndex: 0},
    {q: "¿Qué imperio dominó los Balcanes hasta comienzos del siglo XX?", options: ["El austrohúngaro", "El otomano", "El ruso", "El bizantino"], answerIndex: 1},
    {q: "¿Qué dinastía gobernaba Egipto cuando murió Cleopatra?", options: ["La saíta", "La kushita", "La ptolemaica", "La ramésida"], answerIndex: 2},
  ],

  d3: [
    {q: "¿Qué batalla naval de 1571 enfrentó a la Liga Santa con el Imperio otomano?", options: ["Lepanto", "Accio", "Salamina", "Trafalgar"], answerIndex: 0},
    {q: "¿Qué código legal babilónico es uno de los más antiguos que se conservan?", options: ["El Código de Ur-Nammu", "El Código de Hammurabi", "Las Leyes de Solón", "La Ley de las XII Tablas"], answerIndex: 1},
    {q: "¿Qué emperador romano estableció la Tetrarquía?", options: ["Aureliano", "Trajano", "Diocleciano", "Adriano"], answerIndex: 2},
    {q: "¿Qué cisma dividió la Iglesia cristiana en 1054?", options: ["El Cisma de Occidente", "La Reforma", "El Cisma anglicano", "El Cisma de Oriente"], answerIndex: 3},
    {q: "¿Qué dinastía china unificó el país antes de la dinastía Han?", options: ["La Qin", "La Zhou", "La Shang", "La Sui"], answerIndex: 0},
    {q: "¿Qué rey visigodo se convirtió al catolicismo en el III Concilio de Toledo?", options: ["Leovigildo", "Recaredo", "Alarico", "Wamba"], answerIndex: 1},
    {q: "¿Qué batalla del año 732 frenó el avance musulmán en Europa occidental?", options: ["Covadonga", "Guadalete", "Poitiers", "Las Navas de Tolosa"], answerIndex: 2},
    {q: "¿Qué movimiento religioso inició Martín Lutero en 1517?", options: ["La Contrarreforma", "El Cisma de Oriente", "El jansenismo", "La Reforma protestante"], answerIndex: 3},
    {q: "¿Qué imperio precolombino tuvo su capital en Cuzco?", options: ["El Inca", "El Azteca", "El Chimú", "El Mochica"], answerIndex: 0},
    {q: "¿Qué guerra enfrentó a Rusia y Japón entre 1904 y 1905?", options: ["La Guerra de Crimea", "La Guerra Ruso-Japonesa", "La Guerra Chino-Japonesa", "La Guerra de Manchuria"], answerIndex: 1},
    {q: "¿Qué gobernante mongol fundó la dinastía Yuan en China?", options: ["Gengis Kan", "Ogodei", "Kublai Kan", "Tamerlán"], answerIndex: 2},
    {q: "¿Qué tratado puso fin a la Guerra de Sucesión Española en 1713?", options: ["El de Westfalia", "El de Ryswick", "El de los Pirineos", "El de Utrecht"], answerIndex: 3},
    {q: "¿Qué mujer gobernó Egipto como faraón durante la dinastía XVIII?", options: ["Hatshepsut", "Nefertiti", "Nefertari", "Tiy"], answerIndex: 0},
    {q: "¿Qué nombre recibe la revuelta de esclavos liderada por Espartaco?", options: ["La Guerra Social", "La Tercera Guerra Servil", "La Conjuración de Catilina", "La Guerra de los Aliados"], answerIndex: 1},
    {q: "¿Qué ciudad-estado italiana fue una potencia marítima gobernada por un dux?", options: ["Florencia", "Milán", "Venecia", "Nápoles"], answerIndex: 2},
    {q: "¿En qué año se disolvió oficialmente la Unión Soviética?", options: ["1985", "1989", "1990", "1991"], answerIndex: 3},
    {q: "¿Qué conferencia de 1884-1885 repartió África entre las potencias europeas?", options: ["La Conferencia de Berlín", "El Congreso de Viena", "La Conferencia de Algeciras", "El Congreso de Berlín de 1878"], answerIndex: 0},
  ],
};
