module.exports = {
  d1: [
    {q: "¿En qué año llegó el ser humano a la Luna por primera vez?", options: ["1969", "1981", "1975", "1959"], answerIndex: 0},
    {q: "¿Qué civilización antigua construyó las pirámides de Guiza?", options: ["La fenicia", "La egipcia", "La persa", "La griega"], answerIndex: 1},
    {q: "¿Quién lideró la Alemania nazi durante la Segunda Guerra Mundial?", options: ["Adolf Hitler", "Joseph Goebbels", "Hermann Göring", "Heinrich Himmler"], answerIndex: 0},
    {q: "¿Qué barco se hundió en 1912 tras chocar contra un iceberg?", options: ["El Bismarck", "El Britannic", "El Titanic", "El Lusitania"], answerIndex: 2},
    {q: "¿Qué civilización antigua creó los Juegos Olímpicos?", options: ["La china", "La egipcia", "La romana", "La griega"], answerIndex: 3},
    {q: "¿En qué país se construyó el Taj Mahal?", options: ["India", "Irán", "Turquía", "Pakistán"], answerIndex: 0},
    {q: "¿Qué antigua ciudad romana quedó sepultada por la erupción del Vesubio?", options: ["Ostia", "Éfeso", "Cartago", "Pompeya"], answerIndex: 3},
    {q: "¿Quién fue la primera mujer en recibir un Premio Nobel?", options: ["Lise Meitner", "Marie Curie", "Ada Lovelace", "Rosalind Franklin"], answerIndex: 1},
    {q: "¿Qué invento de Johannes Gutenberg revolucionó la difusión del conocimiento?", options: ["El papel", "La imprenta", "La brújula", "El telescopio"], answerIndex: 1},
    {q: "¿En qué continente aparecieron los primeros seres humanos según la evidencia científica?", options: ["Europa", "Oceanía", "África", "Asia"], answerIndex: 2},
    {q: "¿Qué rey inglés del siglo XVI tuvo seis esposas?", options: ["Jacobo I", "Eduardo VI", "Ricardo III", "Enrique VIII"], answerIndex: 3},
    {q: "¿Qué gran conflicto mundial ocurrió entre 1914 y 1918?", options: ["La Primera Guerra Mundial", "La Guerra de Corea", "La Segunda Guerra Mundial", "La Guerra Fría"], answerIndex: 0},
    {q: "¿Quién pronunció el discurso \"I have a dream\" en 1963?", options: ["Nelson Mandela", "Malcolm X", "Rosa Parks", "Martin Luther King"], answerIndex: 3},
    {q: "¿Qué barco llevó a los peregrinos ingleses a América en 1620?", options: ["El Beagle", "El Victoria", "El Mayflower", "El Santa María"], answerIndex: 2},
    {q: "¿Qué imperio antiguo era gobernado por los faraones?", options: ["El persa", "El asirio", "El egipcio", "El babilónico"], answerIndex: 2},
    {q: "¿Qué material dio nombre a la Edad de Bronce?", options: ["El oro", "El hierro", "La piedra", "El bronce"], answerIndex: 3},
  ],

  d2: [
    {q: "¿Qué revolución comenzó con la toma de la Bastilla en 1789?", options: ["La Revolución Rusa", "La Revolución Americana", "La Revolución Francesa", "La Revolución Industrial"], answerIndex: 2},
    {q: "¿Quién fue el primer emperador de Roma?", options: ["Tiberio", "Nerón", "Julio César", "Augusto"], answerIndex: 3},
    {q: "¿Qué general cartaginés cruzó los Alpes con elefantes para atacar Roma?", options: ["Escipión", "Amílcar Barca", "Asdrúbal", "Aníbal"], answerIndex: 3},
    {q: "¿Qué tratado firmado en 1957 creó la Comunidad Económica Europea?", options: ["El Tratado de Maastricht", "El Tratado de Roma", "El Tratado de Lisboa", "El Tratado de París"], answerIndex: 1},
    {q: "¿Qué rey de Macedonia conquistó el Imperio persa?", options: ["Ptolomeo I", "Filipo II", "Alejandro Magno", "Seleuco"], answerIndex: 2},
    {q: "¿Qué civilización de Mesopotamia desarrolló la escritura cuneiforme?", options: ["Los arameos", "Los sumerios", "Los hititas", "Los medos"], answerIndex: 1},
    {q: "¿Quién fue el primer ser humano en viajar al espacio?", options: ["Valentina Tereshkova", "Neil Armstrong", "Alan Shepard", "Yuri Gagarin"], answerIndex: 3},
    {q: "¿En qué año comenzó la Primera Guerra Mundial?", options: ["1914", "1912", "1918", "1920"], answerIndex: 0},
    {q: "¿Qué nombre recibe el enfrentamiento entre Estados Unidos y la URSS sin combate directo?", options: ["La Guerra de Vietnam", "La Guerra Fría", "La Guerra del Golfo", "La Guerra de Corea"], answerIndex: 1},
    {q: "¿Qué presidente estadounidense impulsó la abolición de la esclavitud?", options: ["Ulysses Grant", "Thomas Jefferson", "Abraham Lincoln", "Andrew Jackson"], answerIndex: 2},
    {q: "¿Qué expedición completó la primera vuelta al mundo?", options: ["La de Francis Drake", "La de Américo Vespucio", "La de Vasco da Gama", "La de Magallanes y Elcano"], answerIndex: 3},
    {q: "¿Qué epidemia devastó Europa a mediados del siglo XIV?", options: ["La gripe española", "La peste negra", "La viruela", "El cólera"], answerIndex: 1},
    {q: "¿Qué líder sudafricano pasó 27 años en prisión antes de ser presidente?", options: ["Nelson Mandela", "Desmond Tutu", "Steve Biko", "Thabo Mbeki"], answerIndex: 0},
    {q: "¿Qué civilización mesoamericana construyó ciudades como Tikal y Palenque?", options: ["La olmeca", "La maya", "La zapoteca", "La tolteca"], answerIndex: 1},
    {q: "¿Qué guerra enfrentó a Atenas y Esparta en la antigua Grecia?", options: ["La Guerra del Peloponeso", "Las Guerras Médicas", "Las Guerras Púnicas", "La Guerra de Troya"], answerIndex: 0},
    {q: "¿En qué año se fundó la Organización de las Naciones Unidas?", options: ["1919", "1950", "1945", "1939"], answerIndex: 2},
    {q: "¿Qué revolución de 1959 llevó a Fidel Castro al poder?", options: ["La Revolución sandinista", "La Revolución cubana", "La Revolución mexicana", "La Revolución boliviana"], answerIndex: 1},
    {q: "¿Qué muro defensivo construyeron los romanos en el norte de Britania?", options: ["El muro de Adriano", "La muralla Aureliana", "El muro de Antonino Pío", "El limes germánico"], answerIndex: 0},
    {q: "¿Qué documento inglés de 1215 limitó el poder del monarca?", options: ["La Carta Magna", "El Acta de Unión", "El Bill of Rights", "La Petición de Derechos"], answerIndex: 0},
    {q: "¿Quién lideró la independencia de Venezuela, Colombia, Ecuador y Bolivia?", options: ["Antonio José de Sucre", "Francisco de Miranda", "Simón Bolívar", "José de San Martín"], answerIndex: 2},
    {q: "¿Qué país lanzó el Sputnik, el primer satélite artificial?", options: ["Alemania", "Reino Unido", "Estados Unidos", "La Unión Soviética"], answerIndex: 3},
    {q: "¿Qué imperio africano medieval fue célebre por su oro y por Mansa Musa?", options: ["Malí", "Ghana", "Kanem-Bornu", "Songhay"], answerIndex: 0},
    {q: "¿En qué año terminó la Primera Guerra Mundial?", options: ["1917", "1918", "1919", "1916"], answerIndex: 1},
    {q: "¿Sobre qué ciudad japonesa se lanzó la primera bomba atómica?", options: ["Kioto", "Tokio", "Nagasaki", "Hiroshima"], answerIndex: 3},
    {q: "¿Qué explorador noruego alcanzó primero el Polo Sur?", options: ["Roald Amundsen", "Fridtjof Nansen", "Ernest Shackleton", "Robert Falcon Scott"], answerIndex: 0},
    {q: "¿Qué imperio dominó los Balcanes hasta comienzos del siglo XX?", options: ["El otomano", "El bizantino", "El ruso", "El austrohúngaro"], answerIndex: 0},
    {q: "¿Qué dinastía gobernaba Egipto cuando murió Cleopatra?", options: ["La ptolemaica", "La saíta", "La ramésida", "La kushita"], answerIndex: 0},
  ],

  d3: [
    {q: "¿Qué batalla naval de 1571 enfrentó a la Liga Santa con el Imperio otomano?", options: ["Trafalgar", "Salamina", "Lepanto", "Accio"], answerIndex: 2},
    {q: "¿Qué código legal babilónico es uno de los más antiguos que se conservan?", options: ["Las Leyes de Solón", "El Código de Hammurabi", "La Ley de las XII Tablas", "El Código de Ur-Nammu"], answerIndex: 1},
    {q: "¿Qué emperador romano estableció la Tetrarquía?", options: ["Aureliano", "Adriano", "Diocleciano", "Trajano"], answerIndex: 2},
    {q: "¿Qué cisma dividió la Iglesia cristiana en 1054?", options: ["El Cisma de Oriente", "El Cisma de Occidente", "El Cisma anglicano", "La Reforma"], answerIndex: 0},
    {q: "¿Qué dinastía china unificó el país antes de la dinastía Han?", options: ["La Sui", "La Zhou", "La Shang", "La Qin"], answerIndex: 3},
    {q: "¿Qué rey visigodo se convirtió al catolicismo en el III Concilio de Toledo?", options: ["Alarico", "Wamba", "Recaredo", "Leovigildo"], answerIndex: 2},
    {q: "¿Qué batalla del año 732 frenó el avance musulmán en Europa occidental?", options: ["Guadalete", "Poitiers", "Las Navas de Tolosa", "Covadonga"], answerIndex: 1},
    {q: "¿Qué movimiento religioso inició Martín Lutero en 1517?", options: ["La Reforma protestante", "El jansenismo", "La Contrarreforma", "El Cisma de Oriente"], answerIndex: 0},
    {q: "¿Qué imperio precolombino tuvo su capital en Cuzco?", options: ["El Azteca", "El Mochica", "El Chimú", "El Inca"], answerIndex: 3},
    {q: "¿Qué guerra enfrentó a Rusia y Japón entre 1904 y 1905?", options: ["La Guerra Chino-Japonesa", "La Guerra de Manchuria", "La Guerra de Crimea", "La Guerra Ruso-Japonesa"], answerIndex: 3},
    {q: "¿Qué gobernante mongol fundó la dinastía Yuan en China?", options: ["Tamerlán", "Gengis Kan", "Kublai Kan", "Ogodei"], answerIndex: 2},
    {q: "¿Qué tratado puso fin a la Guerra de Sucesión Española en 1713?", options: ["El de Westfalia", "El de Ryswick", "El de los Pirineos", "El de Utrecht"], answerIndex: 3},
    {q: "¿Qué mujer gobernó Egipto como faraón durante la dinastía XVIII?", options: ["Nefertiti", "Nefertari", "Tiy", "Hatshepsut"], answerIndex: 3},
    {q: "¿Qué nombre recibe la revuelta de esclavos liderada por Espartaco?", options: ["La Guerra de los Aliados", "La Guerra Social", "La Conjuración de Catilina", "La Tercera Guerra Servil"], answerIndex: 3},
    {q: "¿Qué ciudad-estado italiana fue una potencia marítima gobernada por un dux?", options: ["Florencia", "Milán", "Venecia", "Nápoles"], answerIndex: 2},
    {q: "¿En qué año se disolvió oficialmente la Unión Soviética?", options: ["1989", "1985", "1990", "1991"], answerIndex: 3},
    {q: "¿Qué conferencia de 1884-1885 repartió África entre las potencias europeas?", options: ["La Conferencia de Berlín", "La Conferencia de Algeciras", "El Congreso de Viena", "El Congreso de Berlín de 1878"], answerIndex: 0},
  ],
};
