module.exports = {
  d1: [
    {q: "¿Quién escribió \"La Odisea\"?", options: ["Homero", "Virgilio", "Sófocles", "Esopo"], answerIndex: 0},
    {q: "¿Qué autor escribió \"Alicia en el país de las maravillas\"?", options: ["J. M. Barrie", "Lewis Carroll", "Roald Dahl", "C. S. Lewis"], answerIndex: 1},
    {q: "¿Qué libro narra la historia de un niño criado por animales en la jungla?", options: ["El principito", "Peter Pan", "El libro de la selva", "Bambi"], answerIndex: 2},
    {q: "¿Quién escribió \"Los tres mosqueteros\"?", options: ["Victor Hugo", "Julio Verne", "Émile Zola", "Alejandro Dumas"], answerIndex: 3},
    {q: "¿Qué autor escribió \"Veinte mil leguas de viaje submarino\"?", options: ["Julio Verne", "H. G. Wells", "Daniel Defoe", "Jonathan Swift"], answerIndex: 0},
    {q: "¿Cómo se llama el escudero que acompaña a Don Quijote?", options: ["Dulcinea", "Sancho Panza", "Rocinante", "Cide Hamete"], answerIndex: 1},
    {q: "¿Qué escritor danés es autor de cuentos como \"El patito feo\"?", options: ["Los hermanos Grimm", "Charles Perrault", "Hans Christian Andersen", "Esopo"], answerIndex: 2},
    {q: "¿Qué autor italiano creó el personaje de Pinocho?", options: ["Gianni Rodari", "Italo Calvino", "Edmondo De Amicis", "Carlo Collodi"], answerIndex: 3},
    {q: "¿Qué obra comienza con la frase \"En un lugar de la Mancha...\"?", options: ["Don Quijote de la Mancha", "La Celestina", "El Lazarillo de Tormes", "El Cantar de mio Cid"], answerIndex: 0},
    {q: "¿Qué hermanos alemanes recopilaron cuentos como \"Hansel y Gretel\"?", options: ["Los hermanos Marx", "Los hermanos Grimm", "Los hermanos Lumière", "Los hermanos Machado"], answerIndex: 1},
    {q: "¿Qué autor inglés escribió \"Oliver Twist\"?", options: ["Thomas Hardy", "William Thackeray", "Charles Dickens", "Rudyard Kipling"], answerIndex: 2},
    {q: "¿Qué libro recoge las vivencias de una niña judía escondida durante la Segunda Guerra Mundial?", options: ["La ladrona de libros", "El niño con el pijama de rayas", "Si esto es un hombre", "El diario de Ana Frank"], answerIndex: 3},
    {q: "¿Qué autor escocés escribió \"La isla del tesoro\"?", options: ["Robert Louis Stevenson", "Walter Scott", "Arthur Conan Doyle", "J. M. Barrie"], answerIndex: 0},
    {q: "¿Qué escritor estadounidense creó a Tom Sawyer?", options: ["Jack London", "Mark Twain", "Herman Melville", "Washington Irving"], answerIndex: 1},
    {q: "¿Qué autora escribió \"Mujercitas\"?", options: ["Emily Dickinson", "Harriet Beecher Stowe", "Louisa May Alcott", "Edith Wharton"], answerIndex: 2},
    {q: "¿Cómo se llama un texto literario escrito en verso?", options: ["Una novela", "Un ensayo", "Un cuento", "Un poema"], answerIndex: 3},
  ],

  d2: [
    {q: "¿Qué autor irlandés escribió \"El retrato de Dorian Gray\"?", options: ["Oscar Wilde", "Bram Stoker", "George Bernard Shaw", "W. B. Yeats"], answerIndex: 0},
    {q: "¿Qué escritor español, Premio Nobel en 1989, escribió \"La colmena\"?", options: ["Miguel Delibes", "Camilo José Cela", "Juan Goytisolo", "Rafael Sánchez Ferlosio"], answerIndex: 1},
    {q: "¿Qué autor escribió \"Rebelión en la granja\"?", options: ["Aldous Huxley", "Anthony Burgess", "George Orwell", "Evelyn Waugh"], answerIndex: 2},
    {q: "¿Qué poeta italiano escribió \"La Divina Comedia\"?", options: ["Petrarca", "Boccaccio", "Ariosto", "Dante Alighieri"], answerIndex: 3},
    {q: "¿Qué autora británica escribió \"Cumbres borrascosas\"?", options: ["Emily Brontë", "Charlotte Brontë", "George Eliot", "Elizabeth Gaskell"], answerIndex: 0},
    {q: "¿Qué escritor francés escribió \"Los miserables\"?", options: ["Honoré de Balzac", "Victor Hugo", "Stendhal", "Alphonse Daudet"], answerIndex: 1},
    {q: "¿Qué autor ruso escribió \"El maestro y Margarita\"?", options: ["Iván Turguénev", "Antón Chéjov", "Mijaíl Bulgákov", "Borís Pasternak"], answerIndex: 2},
    {q: "¿Qué escritor uruguayo escribió \"La tregua\"?", options: ["Juan Carlos Onetti", "Felisberto Hernández", "Horacio Quiroga", "Mario Benedetti"], answerIndex: 3},
    {q: "¿Qué autor escribió \"En el camino\", obra clave de la generación beat?", options: ["Jack Kerouac", "Allen Ginsberg", "William Burroughs", "Charles Bukowski"], answerIndex: 0},
    {q: "¿Qué escritora mexicana escribió \"Como agua para chocolate\"?", options: ["Elena Poniatowska", "Laura Esquivel", "Rosario Castellanos", "Ángeles Mastretta"], answerIndex: 1},
    {q: "¿Qué autor británico escribió \"El señor de las moscas\"?", options: ["Graham Greene", "E. M. Forster", "William Golding", "Kingsley Amis"], answerIndex: 2},
    {q: "¿Qué escritor japonés escribió \"Tokio blues\"?", options: ["Yukio Mishima", "Kenzaburō Ōe", "Yasunari Kawabata", "Haruki Murakami"], answerIndex: 3},
    {q: "¿Qué autor estadounidense escribió \"El viejo y el mar\"?", options: ["Ernest Hemingway", "John Steinbeck", "William Faulkner", "Truman Capote"], answerIndex: 0},
    {q: "¿Qué escritor irlandés escribió \"Drácula\"?", options: ["Sheridan Le Fanu", "Bram Stoker", "Oscar Wilde", "Arthur Machen"], answerIndex: 1},
    {q: "¿Qué autor sueco escribió \"Los hombres que no amaban a las mujeres\"?", options: ["Henning Mankell", "Jo Nesbø", "Stieg Larsson", "Camilla Läckberg"], answerIndex: 2},
    {q: "¿Qué novela de Anthony Burgess inspiró la película de Kubrick protagonizada por Alex?", options: ["1984", "Un mundo feliz", "Nosotros", "La naranja mecánica"], answerIndex: 3},
    {q: "¿Qué autor escribió \"Fahrenheit 451\"?", options: ["Ray Bradbury", "Isaac Asimov", "Philip K. Dick", "Arthur C. Clarke"], answerIndex: 0},
    {q: "¿Qué escritor argentino escribió \"Sobre héroes y tumbas\"?", options: ["Adolfo Bioy Casares", "Ernesto Sabato", "Leopoldo Marechal", "Roberto Arlt"], answerIndex: 1},
    {q: "¿Qué autora estadounidense ganó el Premio Nobel de Literatura en 1993 por obras como \"Beloved\"?", options: ["Alice Walker", "Joyce Carol Oates", "Toni Morrison", "Maya Angelou"], answerIndex: 2},
    {q: "¿Qué escritor portugués es autor del \"Libro del desasosiego\"?", options: ["Eça de Queirós", "António Lobo Antunes", "Camilo Castelo Branco", "Fernando Pessoa"], answerIndex: 3},
    {q: "¿Qué poeta nicaragüense es considerado el padre del modernismo hispanoamericano?", options: ["Rubén Darío", "José Martí", "Amado Nervo", "Leopoldo Lugones"], answerIndex: 0},
    {q: "¿Qué autora canadiense escribió \"El cuento de la criada\"?", options: ["Alice Munro", "Margaret Atwood", "Ursula K. Le Guin", "Doris Lessing"], answerIndex: 1},
    {q: "¿Qué escritor español escribió \"La sombra del viento\"?", options: ["Javier Marías", "Arturo Pérez-Reverte", "Carlos Ruiz Zafón", "Eduardo Mendoza"], answerIndex: 2},
    {q: "¿Qué autor galés escribió \"Los pilares de la Tierra\"?", options: ["John le Carré", "Frederick Forsyth", "Wilbur Smith", "Ken Follett"], answerIndex: 3},
    {q: "¿Qué escritor estadounidense es conocido por novelas de terror como \"It\"?", options: ["Stephen King", "Dean Koontz", "Clive Barker", "Peter Straub"], answerIndex: 0},
    {q: "¿Qué obra de Homero narra episodios de la guerra de Troya?", options: ["La Eneida", "La Ilíada", "Las Metamorfosis", "La Teogonía"], answerIndex: 1},
    {q: "¿Qué escritor mexicano escribió \"La región más transparente\"?", options: ["Juan José Arreola", "Octavio Paz", "Carlos Fuentes", "Salvador Elizondo"], answerIndex: 2},
  ],

  d3: [
    {q: "¿Qué escritor austríaco escribió las memorias \"El mundo de ayer\"?", options: ["Stefan Zweig", "Robert Musil", "Joseph Roth", "Hermann Broch"], answerIndex: 0},
    {q: "¿Qué autor británico escribió \"Bajo el volcán\", ambientada en México?", options: ["Graham Greene", "Malcolm Lowry", "Aldous Huxley", "D. H. Lawrence"], answerIndex: 1},
    {q: "¿Qué poeta estadounidense escribió \"Hojas de hierba\"?", options: ["Ezra Pound", "T. S. Eliot", "Walt Whitman", "Robert Frost"], answerIndex: 2},
    {q: "¿Qué escritora británica escribió \"La señora Dalloway\"?", options: ["Katherine Mansfield", "Iris Murdoch", "Muriel Spark", "Virginia Woolf"], answerIndex: 3},
    {q: "¿Qué autor francés escribió \"El extranjero\"?", options: ["Albert Camus", "Jean-Paul Sartre", "André Malraux", "Louis-Ferdinand Céline"], answerIndex: 0},
    {q: "¿Qué escritor ruso escribió \"Almas muertas\"?", options: ["Iván Goncharov", "Nikolái Gógol", "Alexander Pushkin", "Mijaíl Lérmontov"], answerIndex: 1},
    {q: "¿Qué autor alemán escribió \"La montaña mágica\"?", options: ["Hermann Hesse", "Günter Grass", "Thomas Mann", "Heinrich Böll"], answerIndex: 2},
    {q: "¿Qué novela del siglo XVIII de Laurence Sterne es célebre por sus digresiones?", options: ["Robinson Crusoe", "Pamela", "Tom Jones", "Tristram Shandy"], answerIndex: 3},
    {q: "¿Qué escritor peruano escribió \"Los ríos profundos\"?", options: ["José María Arguedas", "Ciro Alegría", "Julio Ramón Ribeyro", "Manuel Scorza"], answerIndex: 0},
    {q: "¿Qué poeta chileno escribió \"Veinte poemas de amor y una canción desesperada\"?", options: ["Vicente Huidobro", "Pablo Neruda", "Nicanor Parra", "Gonzalo Rojas"], answerIndex: 1},
    {q: "¿Qué autor italiano escribió \"Si esto es un hombre\", testimonio de Auschwitz?", options: ["Italo Svevo", "Cesare Pavese", "Primo Levi", "Elio Vittorini"], answerIndex: 2},
    {q: "¿Qué escritor cubano escribió \"El siglo de las luces\"?", options: ["José Lezama Lima", "Guillermo Cabrera Infante", "Virgilio Piñera", "Alejo Carpentier"], answerIndex: 3},
    {q: "¿Qué obra de Goethe narra el pacto de un erudito con el diablo?", options: ["Fausto", "Werther", "Egmont", "Ifigenia en Táuride"], answerIndex: 0},
    {q: "¿Qué autor nigeriano escribió \"Todo se desmorona\"?", options: ["Wole Soyinka", "Chinua Achebe", "Ben Okri", "Ngũgĩ wa Thiong'o"], answerIndex: 1},
    {q: "¿Qué escritor francés escribió \"Madame Bovary\"?", options: ["Guy de Maupassant", "Émile Zola", "Gustave Flaubert", "Prosper Mérimée"], answerIndex: 2},
    {q: "¿Qué poeta inglés escribió \"El paraíso perdido\"?", options: ["William Blake", "Geoffrey Chaucer", "Edmund Spenser", "John Milton"], answerIndex: 3},
    {q: "¿Qué escritor guatemalteco ganó el Nobel en 1967, autor de \"El señor Presidente\"?", options: ["Miguel Ángel Asturias", "Augusto Monterroso", "Luis Cardoza y Aragón", "Rodrigo Rey Rosa"], answerIndex: 0},
  ],
};
