module.exports = {
  d1: [
    {q: "¿Quién escribió \"La Odisea\"?", options: ["Homero", "Sófocles", "Esopo", "Virgilio"], answerIndex: 0},
    {q: "¿Qué autor escribió \"Alicia en el país de las maravillas\"?", options: ["J. M. Barrie", "Lewis Carroll", "C. S. Lewis", "Roald Dahl"], answerIndex: 1},
    {q: "¿Qué libro narra la historia de un niño criado por animales en la jungla?", options: ["El principito", "Peter Pan", "El libro de la selva", "Bambi"], answerIndex: 2},
    {q: "¿Quién escribió \"Los tres mosqueteros\"?", options: ["Émile Zola", "Alejandro Dumas", "Victor Hugo", "Julio Verne"], answerIndex: 1},
    {q: "¿Qué autor escribió \"Veinte mil leguas de viaje submarino\"?", options: ["H. G. Wells", "Daniel Defoe", "Julio Verne", "Jonathan Swift"], answerIndex: 2},
    {q: "¿Cómo se llama el escudero que acompaña a Don Quijote?", options: ["Rocinante", "Cide Hamete", "Dulcinea", "Sancho Panza"], answerIndex: 3},
    {q: "¿Qué escritor danés es autor de cuentos como \"El patito feo\"?", options: ["Charles Perrault", "Hans Christian Andersen", "Esopo", "Los hermanos Grimm"], answerIndex: 1},
    {q: "¿Qué autor italiano creó el personaje de Pinocho?", options: ["Italo Calvino", "Carlo Collodi", "Edmondo De Amicis", "Gianni Rodari"], answerIndex: 1},
    {q: "¿Qué obra comienza con la frase \"En un lugar de la Mancha...\"?", options: ["Don Quijote de la Mancha", "El Cantar de mio Cid", "El Lazarillo de Tormes", "La Celestina"], answerIndex: 0},
    {q: "¿Qué hermanos alemanes recopilaron cuentos como \"Hansel y Gretel\"?", options: ["Los hermanos Marx", "Los hermanos Machado", "Los hermanos Grimm", "Los hermanos Lumière"], answerIndex: 2},
    {q: "¿Qué autor inglés escribió \"Oliver Twist\"?", options: ["Thomas Hardy", "Rudyard Kipling", "Charles Dickens", "William Thackeray"], answerIndex: 2},
    {q: "¿Qué libro recoge las vivencias de una niña judía escondida durante la Segunda Guerra Mundial?", options: ["El diario de Ana Frank", "Si esto es un hombre", "La ladrona de libros", "El niño con el pijama de rayas"], answerIndex: 0},
    {q: "¿Qué autor escocés escribió \"La isla del tesoro\"?", options: ["Walter Scott", "Robert Louis Stevenson", "Arthur Conan Doyle", "J. M. Barrie"], answerIndex: 1},
    {q: "¿Qué escritor estadounidense creó a Tom Sawyer?", options: ["Washington Irving", "Jack London", "Herman Melville", "Mark Twain"], answerIndex: 3},
    {q: "¿Qué autora escribió \"Mujercitas\"?", options: ["Harriet Beecher Stowe", "Louisa May Alcott", "Emily Dickinson", "Edith Wharton"], answerIndex: 1},
    {q: "¿Cómo se llama un texto literario escrito en verso?", options: ["Un poema", "Una novela", "Un ensayo", "Un cuento"], answerIndex: 0},
  ],

  d2: [
    {q: "¿Qué autor irlandés escribió \"El retrato de Dorian Gray\"?", options: ["Oscar Wilde", "Bram Stoker", "George Bernard Shaw", "W. B. Yeats"], answerIndex: 0},
    {q: "¿Qué escritor español, Premio Nobel en 1989, escribió \"La colmena\"?", options: ["Rafael Sánchez Ferlosio", "Camilo José Cela", "Miguel Delibes", "Juan Goytisolo"], answerIndex: 1},
    {q: "¿Qué autor escribió \"Rebelión en la granja\"?", options: ["Evelyn Waugh", "George Orwell", "Aldous Huxley", "Anthony Burgess"], answerIndex: 1},
    {q: "¿Qué poeta italiano escribió \"La Divina Comedia\"?", options: ["Ariosto", "Dante Alighieri", "Boccaccio", "Petrarca"], answerIndex: 1},
    {q: "¿Qué autora británica escribió \"Cumbres borrascosas\"?", options: ["George Eliot", "Elizabeth Gaskell", "Charlotte Brontë", "Emily Brontë"], answerIndex: 3},
    {q: "¿Qué escritor francés escribió \"Los miserables\"?", options: ["Stendhal", "Honoré de Balzac", "Victor Hugo", "Alphonse Daudet"], answerIndex: 2},
    {q: "¿Qué autor ruso escribió \"El maestro y Margarita\"?", options: ["Mijaíl Bulgákov", "Iván Turguénev", "Borís Pasternak", "Antón Chéjov"], answerIndex: 0},
    {q: "¿Qué escritor uruguayo escribió \"La tregua\"?", options: ["Felisberto Hernández", "Horacio Quiroga", "Juan Carlos Onetti", "Mario Benedetti"], answerIndex: 3},
    {q: "¿Qué autor escribió \"En el camino\", obra clave de la generación beat?", options: ["Jack Kerouac", "Allen Ginsberg", "William Burroughs", "Charles Bukowski"], answerIndex: 0},
    {q: "¿Qué escritora mexicana escribió \"Como agua para chocolate\"?", options: ["Ángeles Mastretta", "Rosario Castellanos", "Elena Poniatowska", "Laura Esquivel"], answerIndex: 3},
    {q: "¿Qué autor británico escribió \"El señor de las moscas\"?", options: ["William Golding", "Kingsley Amis", "Graham Greene", "E. M. Forster"], answerIndex: 0},
    {q: "¿Qué escritor japonés escribió \"Tokio blues\"?", options: ["Kenzaburō Ōe", "Haruki Murakami", "Yasunari Kawabata", "Yukio Mishima"], answerIndex: 1},
    {q: "¿Qué autor estadounidense escribió \"El viejo y el mar\"?", options: ["Truman Capote", "John Steinbeck", "William Faulkner", "Ernest Hemingway"], answerIndex: 3},
    {q: "¿Qué escritor irlandés escribió \"Drácula\"?", options: ["Oscar Wilde", "Sheridan Le Fanu", "Arthur Machen", "Bram Stoker"], answerIndex: 3},
    {q: "¿Qué autor sueco escribió \"Los hombres que no amaban a las mujeres\"?", options: ["Stieg Larsson", "Camilla Läckberg", "Henning Mankell", "Jo Nesbø"], answerIndex: 0},
    {q: "¿Qué novela de Anthony Burgess inspiró la película de Kubrick protagonizada por Alex?", options: ["La naranja mecánica", "1984", "Nosotros", "Un mundo feliz"], answerIndex: 0},
    {q: "¿Qué autor escribió \"Fahrenheit 451\"?", options: ["Philip K. Dick", "Isaac Asimov", "Arthur C. Clarke", "Ray Bradbury"], answerIndex: 3},
    {q: "¿Qué escritor argentino escribió \"Sobre héroes y tumbas\"?", options: ["Adolfo Bioy Casares", "Leopoldo Marechal", "Roberto Arlt", "Ernesto Sabato"], answerIndex: 3},
    {q: "¿Qué autora estadounidense ganó el Premio Nobel de Literatura en 1993 por obras como \"Beloved\"?", options: ["Alice Walker", "Joyce Carol Oates", "Maya Angelou", "Toni Morrison"], answerIndex: 3},
    {q: "¿Qué escritor portugués es autor del \"Libro del desasosiego\"?", options: ["António Lobo Antunes", "Camilo Castelo Branco", "Fernando Pessoa", "Eça de Queirós"], answerIndex: 2},
    {q: "¿Qué poeta nicaragüense es considerado el padre del modernismo hispanoamericano?", options: ["Leopoldo Lugones", "Amado Nervo", "José Martí", "Rubén Darío"], answerIndex: 3},
    {q: "¿Qué autora canadiense escribió \"El cuento de la criada\"?", options: ["Margaret Atwood", "Ursula K. Le Guin", "Alice Munro", "Doris Lessing"], answerIndex: 0},
    {q: "¿Qué escritor español escribió \"La sombra del viento\"?", options: ["Eduardo Mendoza", "Javier Marías", "Carlos Ruiz Zafón", "Arturo Pérez-Reverte"], answerIndex: 2},
    {q: "¿Qué autor galés escribió \"Los pilares de la Tierra\"?", options: ["John le Carré", "Ken Follett", "Wilbur Smith", "Frederick Forsyth"], answerIndex: 1},
    {q: "¿Qué escritor estadounidense es conocido por novelas de terror como \"It\"?", options: ["Dean Koontz", "Peter Straub", "Clive Barker", "Stephen King"], answerIndex: 3},
    {q: "¿Qué obra de Homero narra episodios de la guerra de Troya?", options: ["La Ilíada", "La Teogonía", "La Eneida", "Las Metamorfosis"], answerIndex: 0},
    {q: "¿Qué escritor mexicano escribió \"La región más transparente\"?", options: ["Octavio Paz", "Juan José Arreola", "Carlos Fuentes", "Salvador Elizondo"], answerIndex: 2},
  ],

  d3: [
    {q: "¿Qué escritor austríaco escribió las memorias \"El mundo de ayer\"?", options: ["Stefan Zweig", "Joseph Roth", "Robert Musil", "Hermann Broch"], answerIndex: 0},
    {q: "¿Qué autor británico escribió \"Bajo el volcán\", ambientada en México?", options: ["Malcolm Lowry", "D. H. Lawrence", "Graham Greene", "Aldous Huxley"], answerIndex: 0},
    {q: "¿Qué poeta estadounidense escribió \"Hojas de hierba\"?", options: ["T. S. Eliot", "Ezra Pound", "Robert Frost", "Walt Whitman"], answerIndex: 3},
    {q: "¿Qué escritora británica escribió \"La señora Dalloway\"?", options: ["Muriel Spark", "Katherine Mansfield", "Virginia Woolf", "Iris Murdoch"], answerIndex: 2},
    {q: "¿Qué autor francés escribió \"El extranjero\"?", options: ["André Malraux", "Jean-Paul Sartre", "Albert Camus", "Louis-Ferdinand Céline"], answerIndex: 2},
    {q: "¿Qué escritor ruso escribió \"Almas muertas\"?", options: ["Nikolái Gógol", "Iván Goncharov", "Mijaíl Lérmontov", "Alexander Pushkin"], answerIndex: 0},
    {q: "¿Qué autor alemán escribió \"La montaña mágica\"?", options: ["Günter Grass", "Thomas Mann", "Heinrich Böll", "Hermann Hesse"], answerIndex: 1},
    {q: "¿Qué novela del siglo XVIII de Laurence Sterne es célebre por sus digresiones?", options: ["Robinson Crusoe", "Pamela", "Tom Jones", "Tristram Shandy"], answerIndex: 3},
    {q: "¿Qué escritor peruano escribió \"Los ríos profundos\"?", options: ["Ciro Alegría", "Manuel Scorza", "Julio Ramón Ribeyro", "José María Arguedas"], answerIndex: 3},
    {q: "¿Qué poeta chileno escribió \"Veinte poemas de amor y una canción desesperada\"?", options: ["Nicanor Parra", "Pablo Neruda", "Vicente Huidobro", "Gonzalo Rojas"], answerIndex: 1},
    {q: "¿Qué autor italiano escribió \"Si esto es un hombre\", testimonio de Auschwitz?", options: ["Elio Vittorini", "Primo Levi", "Cesare Pavese", "Italo Svevo"], answerIndex: 1},
    {q: "¿Qué escritor cubano escribió \"El siglo de las luces\"?", options: ["Guillermo Cabrera Infante", "José Lezama Lima", "Alejo Carpentier", "Virgilio Piñera"], answerIndex: 2},
    {q: "¿Qué obra de Goethe narra el pacto de un erudito con el diablo?", options: ["Werther", "Egmont", "Fausto", "Ifigenia en Táuride"], answerIndex: 2},
    {q: "¿Qué autor nigeriano escribió \"Todo se desmorona\"?", options: ["Wole Soyinka", "Ngũgĩ wa Thiong'o", "Ben Okri", "Chinua Achebe"], answerIndex: 3},
    {q: "¿Qué escritor francés escribió \"Madame Bovary\"?", options: ["Guy de Maupassant", "Gustave Flaubert", "Émile Zola", "Prosper Mérimée"], answerIndex: 1},
    {q: "¿Qué poeta inglés escribió \"El paraíso perdido\"?", options: ["Edmund Spenser", "William Blake", "Geoffrey Chaucer", "John Milton"], answerIndex: 3},
    {q: "¿Qué escritor guatemalteco ganó el Nobel en 1967, autor de \"El señor Presidente\"?", options: ["Luis Cardoza y Aragón", "Rodrigo Rey Rosa", "Augusto Monterroso", "Miguel Ángel Asturias"], answerIndex: 3},
  ],
};
