module.exports = {
  d1: [
    {q: "¿Cuántas notas tiene la escala musical básica de do a si?", options: ["Siete", "Cinco", "Ocho", "Doce"], answerIndex: 0},
    {q: "¿Qué instrumento de viento con llaves es característico del jazz?", options: ["La flauta", "El saxofón", "La trompeta", "El clarinete"], answerIndex: 1},
    {q: "¿Cómo se llama el conjunto de músicos que interpreta música clásica bajo un director?", options: ["El coro", "La banda", "La orquesta", "El cuarteto"], answerIndex: 2},
    {q: "¿Qué objeto usa un director para marcar el ritmo de la orquesta?", options: ["El arco", "La púa", "La baqueta", "La batuta"], answerIndex: 3},
    {q: "¿Qué instrumento de percusión combina tambores y platillos tocados con baquetas?", options: ["La batería", "El xilófono", "El timbal", "La pandereta"], answerIndex: 0},
    {q: "¿De qué país es originario el mariachi?", options: ["Colombia", "México", "Perú", "Argentina"], answerIndex: 1},
    {q: "¿Qué instrumento tiene teclas y se toca abriendo y cerrando un fuelle?", options: ["El órgano", "El clavecín", "El acordeón", "La armónica"], answerIndex: 2},
    {q: "¿Qué género musical brasileño es protagonista del carnaval?", options: ["La bachata", "La cumbia", "El son", "La samba"], answerIndex: 3},
    {q: "¿Cuántas líneas tiene un pentagrama?", options: ["Cinco", "Cuatro", "Seis", "Siete"], answerIndex: 0},
    {q: "¿Qué banda irlandesa tiene a Bono como vocalista?", options: ["Coldplay", "U2", "The Cranberries", "Snow Patrol"], answerIndex: 1},
    {q: "¿Qué instrumento tradicional escocés utiliza un fuelle y varios tubos?", options: ["El laúd", "El banjo", "La gaita", "La cítara"], answerIndex: 2},
    {q: "¿Qué género urbano nació entre Puerto Rico y Panamá?", options: ["El hip hop", "El dancehall", "La cumbia", "El reguetón"], answerIndex: 3},
    {q: "¿Qué cantante británica interpreta \"Rolling in the Deep\"?", options: ["Adele", "Dua Lipa", "Amy Winehouse", "Ellie Goulding"], answerIndex: 0},
    {q: "¿Qué cantante canadiense se hizo famoso con la canción \"Baby\" en 2010?", options: ["Shawn Mendes", "Justin Bieber", "The Weeknd", "Drake"], answerIndex: 1},
    {q: "¿Qué instrumento de cuerda es el más pequeño y agudo de la orquesta?", options: ["La viola", "El violonchelo", "El violín", "El contrabajo"], answerIndex: 2},
    {q: "¿Qué cantante estadounidense es conocida como \"Queen B\"?", options: ["Rihanna", "Mariah Carey", "Alicia Keys", "Beyoncé"], answerIndex: 3},
  ],

  d2: [
    {q: "¿Qué compositor barroco escribió el oratorio \"El Mesías\"?", options: ["Georg Friedrich Händel", "Henry Purcell", "Arcangelo Corelli", "Domenico Scarlatti"], answerIndex: 0},
    {q: "¿Qué banda de Seattle tiene a Eddie Vedder como vocalista?", options: ["Soundgarden", "Pearl Jam", "Alice in Chains", "Stone Temple Pilots"], answerIndex: 1},
    {q: "¿Qué instrumento andino es una flauta formada por varios tubos de distinta longitud?", options: ["La quena", "El charango", "La zampoña", "El bombo"], answerIndex: 2},
    {q: "¿Qué cantante mexicano era conocido como \"El Divo de Juárez\"?", options: ["Vicente Fernández", "José José", "Pedro Infante", "Juan Gabriel"], answerIndex: 3},
    {q: "¿Qué banda estadounidense lideró Jim Morrison?", options: ["The Doors", "Creedence Clearwater Revival", "The Velvet Underground", "Grateful Dead"], answerIndex: 0},
    {q: "¿Qué género musical dominicano se baila en pareja con un ritmo rápido de dos tiempos?", options: ["La bachata", "El merengue", "La salsa", "El son"], answerIndex: 1},
    {q: "¿Qué compositor polaco es célebre por sus nocturnos para piano?", options: ["Franz Liszt", "Robert Schumann", "Frédéric Chopin", "Johannes Brahms"], answerIndex: 2},
    {q: "¿Qué banda británica publicó el álbum \"OK Computer\"?", options: ["Blur", "Oasis", "Muse", "Radiohead"], answerIndex: 3},
    {q: "¿Qué músico estadounidense es conocido como \"The Boss\"?", options: ["Bruce Springsteen", "Tom Petty", "Bob Seger", "John Mellencamp"], answerIndex: 0},
    {q: "¿Qué género cubano es considerado la base rítmica de la salsa?", options: ["El danzón", "El son cubano", "El mambo", "La guaracha"], answerIndex: 1},
    {q: "¿Qué banda australiana grabó \"Highway to Hell\"?", options: ["INXS", "Midnight Oil", "AC/DC", "Men at Work"], answerIndex: 2},
    {q: "¿Qué cantante británica grabó el álbum \"Back to Black\"?", options: ["Duffy", "Lily Allen", "Florence Welch", "Amy Winehouse"], answerIndex: 3},
    {q: "¿Qué compositor ruso escribió \"La consagración de la primavera\"?", options: ["Ígor Stravinski", "Serguéi Prokófiev", "Dmitri Shostakóvich", "Nikolái Rimski-Kórsakov"], answerIndex: 0},
    {q: "¿Cuál es el instrumento más grave de la familia del viento metal?", options: ["El trombón", "La tuba", "La trompa", "El bombardino"], answerIndex: 1},
    {q: "¿Qué género musical estadounidense nació en los Apalaches con banjo y violín?", options: ["El blues", "El country", "El bluegrass", "El gospel"], answerIndex: 2},
    {q: "¿Qué banda británica grabó \"Stairway to Heaven\"?", options: ["Deep Purple", "Black Sabbath", "The Who", "Led Zeppelin"], answerIndex: 3},
    {q: "¿Qué artista española publicó el álbum \"El mal querer\"?", options: ["Rosalía", "Bebe", "Amaral", "La Oreja de Van Gogh"], answerIndex: 0},
    {q: "¿Qué compositor italiano escribió la ópera \"Madama Butterfly\"?", options: ["Gioachino Rossini", "Giacomo Puccini", "Vincenzo Bellini", "Gaetano Donizetti"], answerIndex: 1},
    {q: "¿Qué instrumento de cuerda pulsada tiene siete pedales y unas 47 cuerdas?", options: ["El laúd", "La cítara", "El arpa", "La mandolina"], answerIndex: 2},
    {q: "¿Qué grupo sueco de los años 70 grabó \"Dancing Queen\"?", options: ["Roxette", "Ace of Base", "The Cardigans", "ABBA"], answerIndex: 3},
    {q: "¿Qué género jamaicano precedió al reggae?", options: ["El ska", "El dub", "El calipso", "El soca"], answerIndex: 0},
    {q: "¿Qué cantante colombiano grabó \"La Bicicleta\" junto a Shakira?", options: ["Juanes", "Carlos Vives", "Maluma", "Fonseca"], answerIndex: 1},
    {q: "¿Qué compositor estadounidense escribió \"Rhapsody in Blue\"?", options: ["Aaron Copland", "Leonard Bernstein", "George Gershwin", "Charles Ives"], answerIndex: 2},
    {q: "¿Cuál es la voz femenina más aguda en la ópera?", options: ["La contralto", "La mezzosoprano", "El contratenor", "La soprano"], answerIndex: 3},
    {q: "¿Cuál es el instrumento más grave de un cuarteto de cuerda clásico?", options: ["El violonchelo", "La viola", "El segundo violín", "El contrabajo"], answerIndex: 0},
    {q: "¿Qué banda mexicana de rock grabó \"Rayando el sol\"?", options: ["Café Tacvba", "Maná", "Caifanes", "Molotov"], answerIndex: 1},
    {q: "¿Qué músico argentino, junto a Charly García, es figura fundacional del rock en español?", options: ["Fito Páez", "Andrés Calamaro", "Luis Alberto Spinetta", "Gustavo Cerati"], answerIndex: 2},
  ],

  d3: [
    {q: "¿Qué compositor austríaco escribió el ciclo de canciones \"Winterreise\"?", options: ["Franz Schubert", "Gustav Mahler", "Hugo Wolf", "Anton Bruckner"], answerIndex: 0},
    {q: "¿Qué compositor finlandés escribió el poema sinfónico \"Finlandia\"?", options: ["Carl Nielsen", "Jean Sibelius", "Edvard Grieg", "Niels Gade"], answerIndex: 1},
    {q: "¿Qué término musical indica un aumento gradual del volumen?", options: ["Diminuendo", "Staccato", "Crescendo", "Legato"], answerIndex: 2},
    {q: "¿Qué compositor húngaro recopiló música folclórica junto a Zoltán Kodály?", options: ["Franz Liszt", "Ernő Dohnányi", "György Ligeti", "Béla Bartók"], answerIndex: 3},
    {q: "¿Qué compositor español escribió el ballet \"El amor brujo\"?", options: ["Manuel de Falla", "Isaac Albéniz", "Enrique Granados", "Joaquín Rodrigo"], answerIndex: 0},
    {q: "¿Qué compositor minimalista estadounidense escribió \"Einstein on the Beach\"?", options: ["Steve Reich", "Philip Glass", "Terry Riley", "John Adams"], answerIndex: 1},
    {q: "¿Qué forma musical barroca se basa en la entrada sucesiva de un mismo tema por imitación?", options: ["La sonata", "El rondó", "La fuga", "La tocata"], answerIndex: 2},
    {q: "¿Qué compositor checo escribió la sinfonía \"Del Nuevo Mundo\"?", options: ["Bedřich Smetana", "Leoš Janáček", "Bohuslav Martinů", "Antonín Dvořák"], answerIndex: 3},
    {q: "¿Qué instrumento electrónico se interpreta sin contacto físico con el ejecutante?", options: ["El theremín", "El sintetizador", "El mellotrón", "Las ondas Martenot"], answerIndex: 0},
    {q: "¿Qué compositor francés escribió el \"Bolero\"?", options: ["Claude Debussy", "Maurice Ravel", "Erik Satie", "Camille Saint-Saëns"], answerIndex: 1},
    {q: "¿Qué compositor noruego escribió la música incidental de \"Peer Gynt\"?", options: ["Carl Nielsen", "Johan Svendsen", "Edvard Grieg", "Christian Sinding"], answerIndex: 2},
    {q: "¿Qué compositor ruso escribió la suite \"Cuadros de una exposición\"?", options: ["Aleksandr Borodín", "César Cui", "Mili Balákirev", "Modest Músorgski"], answerIndex: 3},
    {q: "¿Qué cantante estadounidense de jazz era conocida como \"Lady Day\"?", options: ["Billie Holiday", "Ella Fitzgerald", "Sarah Vaughan", "Nina Simone"], answerIndex: 0},
    {q: "¿Qué trompetista grabó el álbum \"Kind of Blue\"?", options: ["Louis Armstrong", "Miles Davis", "Dizzy Gillespie", "Chet Baker"], answerIndex: 1},
    {q: "¿Qué músico argentino renovó el tango dando origen al llamado nuevo tango?", options: ["Aníbal Troilo", "Osvaldo Pugliese", "Astor Piazzolla", "Juan D'Arienzo"], answerIndex: 2},
    {q: "¿Qué compositor alemán del Romanticismo escribió el \"Concierto para violín en mi menor\"?", options: ["Robert Schumann", "Max Bruch", "Carl Maria von Weber", "Felix Mendelssohn"], answerIndex: 3},
    {q: "¿Cómo se llama el tema principal que expone una fuga al comienzo?", options: ["El sujeto", "El estribillo", "La coda", "El puente"], answerIndex: 0},
  ],
};
