module.exports = {
  d1: [
    {q: "¿Cuántas notas tiene la escala musical básica de do a si?", options: ["Doce", "Ocho", "Siete", "Cinco"], answerIndex: 2},
    {q: "¿Qué instrumento de viento con llaves es característico del jazz?", options: ["El saxofón", "El clarinete", "La trompeta", "La flauta"], answerIndex: 0},
    {q: "¿Cómo se llama el conjunto de músicos que interpreta música clásica bajo un director?", options: ["La orquesta", "El coro", "El cuarteto", "La banda"], answerIndex: 0},
    {q: "¿Qué objeto usa un director para marcar el ritmo de la orquesta?", options: ["La baqueta", "El arco", "La púa", "La batuta"], answerIndex: 3},
    {q: "¿Qué instrumento de percusión combina tambores y platillos tocados con baquetas?", options: ["La batería", "El xilófono", "La pandereta", "El timbal"], answerIndex: 0},
    {q: "¿De qué país es originario el mariachi?", options: ["Colombia", "Perú", "México", "Argentina"], answerIndex: 2},
    {q: "¿Qué instrumento tiene teclas y se toca abriendo y cerrando un fuelle?", options: ["El acordeón", "El órgano", "La armónica", "El clavecín"], answerIndex: 0},
    {q: "¿Qué género musical brasileño es protagonista del carnaval?", options: ["La bachata", "La samba", "El son", "La cumbia"], answerIndex: 1},
    {q: "¿Cuántas líneas tiene un pentagrama?", options: ["Siete", "Seis", "Cuatro", "Cinco"], answerIndex: 3},
    {q: "¿Qué banda irlandesa tiene a Bono como vocalista?", options: ["U2", "The Cranberries", "Snow Patrol", "Coldplay"], answerIndex: 0},
    {q: "¿Qué instrumento tradicional escocés utiliza un fuelle y varios tubos?", options: ["La gaita", "El banjo", "La cítara", "El laúd"], answerIndex: 0},
    {q: "¿Qué género urbano nació entre Puerto Rico y Panamá?", options: ["El reguetón", "La cumbia", "El hip hop", "El dancehall"], answerIndex: 0},
    {q: "¿Qué cantante británica interpreta \"Rolling in the Deep\"?", options: ["Amy Winehouse", "Dua Lipa", "Adele", "Ellie Goulding"], answerIndex: 2},
    {q: "¿Qué cantante canadiense se hizo famoso con la canción \"Baby\" en 2010?", options: ["Shawn Mendes", "The Weeknd", "Drake", "Justin Bieber"], answerIndex: 3},
    {q: "¿Qué instrumento de cuerda es el más pequeño y agudo de la orquesta?", options: ["El violonchelo", "La viola", "El contrabajo", "El violín"], answerIndex: 3},
    {q: "¿Qué cantante estadounidense es conocida como \"Queen B\"?", options: ["Rihanna", "Beyoncé", "Mariah Carey", "Alicia Keys"], answerIndex: 1},
  ],

  d2: [
    {q: "¿Qué compositor barroco escribió el oratorio \"El Mesías\"?", options: ["Georg Friedrich Händel", "Domenico Scarlatti", "Arcangelo Corelli", "Henry Purcell"], answerIndex: 0},
    {q: "¿Qué banda de Seattle tiene a Eddie Vedder como vocalista?", options: ["Alice in Chains", "Stone Temple Pilots", "Soundgarden", "Pearl Jam"], answerIndex: 3},
    {q: "¿Qué instrumento andino es una flauta formada por varios tubos de distinta longitud?", options: ["La quena", "La zampoña", "El charango", "El bombo"], answerIndex: 1},
    {q: "¿Qué cantante mexicano era conocido como \"El Divo de Juárez\"?", options: ["José José", "Vicente Fernández", "Pedro Infante", "Juan Gabriel"], answerIndex: 3},
    {q: "¿Qué banda estadounidense lideró Jim Morrison?", options: ["Grateful Dead", "Creedence Clearwater Revival", "The Velvet Underground", "The Doors"], answerIndex: 3},
    {q: "¿Qué género musical dominicano se baila en pareja con un ritmo rápido de dos tiempos?", options: ["La salsa", "El son", "La bachata", "El merengue"], answerIndex: 3},
    {q: "¿Qué compositor polaco es célebre por sus nocturnos para piano?", options: ["Johannes Brahms", "Frédéric Chopin", "Franz Liszt", "Robert Schumann"], answerIndex: 1},
    {q: "¿Qué banda británica publicó el álbum \"OK Computer\"?", options: ["Muse", "Radiohead", "Oasis", "Blur"], answerIndex: 1},
    {q: "¿Qué músico estadounidense es conocido como \"The Boss\"?", options: ["Bob Seger", "Bruce Springsteen", "Tom Petty", "John Mellencamp"], answerIndex: 1},
    {q: "¿Qué género cubano es considerado la base rítmica de la salsa?", options: ["La guaracha", "El son cubano", "El danzón", "El mambo"], answerIndex: 1},
    {q: "¿Qué banda australiana grabó \"Highway to Hell\"?", options: ["INXS", "Men at Work", "Midnight Oil", "AC/DC"], answerIndex: 3},
    {q: "¿Qué cantante británica grabó el álbum \"Back to Black\"?", options: ["Amy Winehouse", "Florence Welch", "Duffy", "Lily Allen"], answerIndex: 0},
    {q: "¿Qué compositor ruso escribió \"La consagración de la primavera\"?", options: ["Serguéi Prokófiev", "Ígor Stravinski", "Dmitri Shostakóvich", "Nikolái Rimski-Kórsakov"], answerIndex: 1},
    {q: "¿Cuál es el instrumento más grave de la familia del viento metal?", options: ["El bombardino", "La tuba", "La trompa", "El trombón"], answerIndex: 1},
    {q: "¿Qué género musical estadounidense nació en los Apalaches con banjo y violín?", options: ["El gospel", "El country", "El blues", "El bluegrass"], answerIndex: 3},
    {q: "¿Qué banda británica grabó \"Stairway to Heaven\"?", options: ["Black Sabbath", "Deep Purple", "Led Zeppelin", "The Who"], answerIndex: 2},
    {q: "¿Qué artista española publicó el álbum \"El mal querer\"?", options: ["La Oreja de Van Gogh", "Bebe", "Rosalía", "Amaral"], answerIndex: 2},
    {q: "¿Qué compositor italiano escribió la ópera \"Madama Butterfly\"?", options: ["Gaetano Donizetti", "Vincenzo Bellini", "Giacomo Puccini", "Gioachino Rossini"], answerIndex: 2},
    {q: "¿Qué instrumento de cuerda pulsada tiene siete pedales y unas 47 cuerdas?", options: ["El arpa", "El laúd", "La mandolina", "La cítara"], answerIndex: 0},
    {q: "¿Qué grupo sueco de los años 70 grabó \"Dancing Queen\"?", options: ["Roxette", "Ace of Base", "The Cardigans", "ABBA"], answerIndex: 3},
    {q: "¿Qué género jamaicano precedió al reggae?", options: ["El calipso", "El soca", "El ska", "El dub"], answerIndex: 2},
    {q: "¿Qué cantante colombiano grabó \"La Bicicleta\" junto a Shakira?", options: ["Carlos Vives", "Maluma", "Juanes", "Fonseca"], answerIndex: 0},
    {q: "¿Qué compositor estadounidense escribió \"Rhapsody in Blue\"?", options: ["Leonard Bernstein", "Aaron Copland", "George Gershwin", "Charles Ives"], answerIndex: 2},
    {q: "¿Cuál es la voz femenina más aguda en la ópera?", options: ["El contratenor", "La mezzosoprano", "La contralto", "La soprano"], answerIndex: 3},
    {q: "¿Cuál es el instrumento más grave de un cuarteto de cuerda clásico?", options: ["El segundo violín", "El violonchelo", "La viola", "El contrabajo"], answerIndex: 1},
    {q: "¿Qué banda mexicana de rock grabó \"Rayando el sol\"?", options: ["Maná", "Caifanes", "Molotov", "Café Tacvba"], answerIndex: 0},
    {q: "¿Qué músico argentino, junto a Charly García, es figura fundacional del rock en español?", options: ["Fito Páez", "Gustavo Cerati", "Andrés Calamaro", "Luis Alberto Spinetta"], answerIndex: 3},
  ],

  d3: [
    {q: "¿Qué compositor austríaco escribió el ciclo de canciones \"Winterreise\"?", options: ["Hugo Wolf", "Franz Schubert", "Gustav Mahler", "Anton Bruckner"], answerIndex: 1},
    {q: "¿Qué compositor finlandés escribió el poema sinfónico \"Finlandia\"?", options: ["Edvard Grieg", "Niels Gade", "Carl Nielsen", "Jean Sibelius"], answerIndex: 3},
    {q: "¿Qué término musical indica un aumento gradual del volumen?", options: ["Diminuendo", "Legato", "Crescendo", "Staccato"], answerIndex: 2},
    {q: "¿Qué compositor húngaro recopiló música folclórica junto a Zoltán Kodály?", options: ["Béla Bartók", "Franz Liszt", "Ernő Dohnányi", "György Ligeti"], answerIndex: 0},
    {q: "¿Qué compositor español escribió el ballet \"El amor brujo\"?", options: ["Manuel de Falla", "Joaquín Rodrigo", "Isaac Albéniz", "Enrique Granados"], answerIndex: 0},
    {q: "¿Qué compositor minimalista estadounidense escribió \"Einstein on the Beach\"?", options: ["John Adams", "Terry Riley", "Steve Reich", "Philip Glass"], answerIndex: 3},
    {q: "¿Qué forma musical barroca se basa en la entrada sucesiva de un mismo tema por imitación?", options: ["La tocata", "La sonata", "La fuga", "El rondó"], answerIndex: 2},
    {q: "¿Qué compositor checo escribió la sinfonía \"Del Nuevo Mundo\"?", options: ["Antonín Dvořák", "Leoš Janáček", "Bedřich Smetana", "Bohuslav Martinů"], answerIndex: 0},
    {q: "¿Qué instrumento electrónico se interpreta sin contacto físico con el ejecutante?", options: ["Las ondas Martenot", "El mellotrón", "El theremín", "El sintetizador"], answerIndex: 2},
    {q: "¿Qué compositor francés escribió el \"Bolero\"?", options: ["Erik Satie", "Camille Saint-Saëns", "Maurice Ravel", "Claude Debussy"], answerIndex: 2},
    {q: "¿Qué compositor noruego escribió la música incidental de \"Peer Gynt\"?", options: ["Carl Nielsen", "Christian Sinding", "Edvard Grieg", "Johan Svendsen"], answerIndex: 2},
    {q: "¿Qué compositor ruso escribió la suite \"Cuadros de una exposición\"?", options: ["Aleksandr Borodín", "César Cui", "Modest Músorgski", "Mili Balákirev"], answerIndex: 2},
    {q: "¿Qué cantante estadounidense de jazz era conocida como \"Lady Day\"?", options: ["Billie Holiday", "Sarah Vaughan", "Nina Simone", "Ella Fitzgerald"], answerIndex: 0},
    {q: "¿Qué trompetista grabó el álbum \"Kind of Blue\"?", options: ["Louis Armstrong", "Miles Davis", "Chet Baker", "Dizzy Gillespie"], answerIndex: 1},
    {q: "¿Qué músico argentino renovó el tango dando origen al llamado nuevo tango?", options: ["Astor Piazzolla", "Juan D'Arienzo", "Osvaldo Pugliese", "Aníbal Troilo"], answerIndex: 0},
    {q: "¿Qué compositor alemán del Romanticismo escribió el \"Concierto para violín en mi menor\"?", options: ["Robert Schumann", "Max Bruch", "Carl Maria von Weber", "Felix Mendelssohn"], answerIndex: 3},
    {q: "¿Cómo se llama el tema principal que expone una fuga al comienzo?", options: ["El estribillo", "El sujeto", "El puente", "La coda"], answerIndex: 1},
  ],
};
