module.exports = {
  d1: [
    {q: "¿De qué color es la gorra de Mario?", options: ["Roja", "Verde", "Azul", "Amarilla"], answerIndex: 0},
    {q: "¿Cómo se llama el hermano de Mario?", options: ["Wario", "Luigi", "Toad", "Waluigi"], answerIndex: 1},
    {q: "¿Qué Pokémon amarillo de tipo eléctrico es la mascota de la saga?", options: ["Charmander", "Bulbasaur", "Pikachu", "Squirtle"], answerIndex: 2},
    {q: "¿Qué juego consiste en encajar piezas geométricas que caen desde arriba?", options: ["Candy Crush", "Bejeweled", "Pac-Man", "Tetris"], answerIndex: 3},
    {q: "¿Cómo se llama la princesa que Mario suele rescatar?", options: ["Peach", "Zelda", "Daisy", "Rosalina"], answerIndex: 0},
    {q: "¿Qué tipo de animal es Sonic?", options: ["Un zorro", "Un erizo", "Un ratón", "Una ardilla"], answerIndex: 1},
    {q: "¿Cómo se llama el dinosaurio verde que acompaña a Mario?", options: ["Bowser", "Koopa", "Yoshi", "Goomba"], answerIndex: 2},
    {q: "¿Qué saga de Nintendo consiste en carreras de karts?", options: ["Mario Party", "Mario Golf", "Mario Tennis", "Mario Kart"], answerIndex: 3},
    {q: "¿En qué videojuego se juega al fútbol conduciendo automóviles?", options: ["Rocket League", "FIFA Street", "Trackmania", "Fall Guys"], answerIndex: 0},
    {q: "¿Qué saga de lucha incluye a Ryu y Chun-Li?", options: ["Tekken", "Street Fighter", "Mortal Kombat", "King of Fighters"], answerIndex: 1},
    {q: "¿Qué consola portátil de Nintendo se caracterizaba por tener dos pantallas?", options: ["Game Boy", "PSP", "Nintendo DS", "Game Gear"], answerIndex: 2},
    {q: "¿Qué significan las siglas \"RPG\" en los videojuegos?", options: ["Juego de disparos", "Juego de carreras", "Juego de estrategia", "Juego de rol"], answerIndex: 3},
    {q: "¿Con qué dispositivo se juega normalmente en una consola?", options: ["El mando", "El ratón", "La tableta", "El micrófono"], answerIndex: 0},
    {q: "¿Qué juego de disparos por equipos de Blizzard incluye a la heroína Tracer?", options: ["Valorant", "Overwatch", "Team Fortress", "Paladins"], answerIndex: 1},
    {q: "¿Qué enemigo con caparazón y cuernos es el villano principal de Mario?", options: ["Donkey Kong", "King Boo", "Bowser", "Kamek"], answerIndex: 2},
    {q: "¿Qué saga de Nintendo protagoniza una cazarrecompensas llamada Samus Aran?", options: ["Kirby", "Star Fox", "F-Zero", "Metroid"], answerIndex: 3},
  ],

  d2: [
    {q: "¿Qué estudio desarrolló la saga \"God of War\"?", options: ["Santa Monica Studio", "Sucker Punch", "Insomniac Games", "Guerrilla Games"], answerIndex: 0},
    {q: "¿Qué juego de 2017 renovó la saga Zelda con un enorme mundo abierto?", options: ["Skyward Sword", "Breath of the Wild", "Twilight Princess", "A Link Between Worlds"], answerIndex: 1},
    {q: "¿En qué ciudad ficticia transcurre \"Cyberpunk 2077\"?", options: ["Neo Tokio", "Rapture", "Night City", "Midgar"], answerIndex: 2},
    {q: "¿Qué saga de Bethesda transcurre en un mundo postnuclear con refugios llamados Vault?", options: ["BioShock", "Metro", "Wasteland", "Fallout"], answerIndex: 3},
    {q: "¿Qué juego de rol de Bethesda transcurre en la región de Skyrim?", options: ["The Elder Scrolls V", "Dragon Age", "Divinity", "Gothic"], answerIndex: 0},
    {q: "¿Qué compañía desarrolló \"Overwatch\"?", options: ["Valve", "Blizzard", "Riot Games", "Bungie"], answerIndex: 1},
    {q: "¿Qué saga de estrategia en tiempo real de Blizzard enfrenta a orcos y humanos?", options: ["Age of Empires", "Command & Conquer", "Warcraft", "Total War"], answerIndex: 2},
    {q: "¿Qué videojuego de Valve se basa en resolver puzles con un arma que crea portales?", options: ["Half-Life", "Antichamber", "The Talos Principle", "Portal"], answerIndex: 3},
    {q: "¿Qué plataforma digital de distribución de juegos para PC creó Valve?", options: ["Steam", "Epic Games Store", "GOG", "Origin"], answerIndex: 0},
    {q: "¿Qué saga de Konami protagoniza el soldado Solid Snake?", options: ["Splinter Cell", "Metal Gear Solid", "Hitman", "Syphon Filter"], answerIndex: 1},
    {q: "¿Qué juego de Nintendo enfrenta en combate a personajes de distintas sagas?", options: ["Mario Party", "Nintendo Land", "Super Smash Bros.", "Wii Sports"], answerIndex: 2},
    {q: "¿Qué juego indie de plataformas protagoniza un insecto en el reino de Hallownest?", options: ["Celeste", "Ori and the Blind Forest", "Dead Cells", "Hollow Knight"], answerIndex: 3},
    {q: "¿Qué compañía desarrolló \"League of Legends\"?", options: ["Riot Games", "Valve", "Blizzard", "Tencent Games"], answerIndex: 0},
    {q: "¿A qué género pertenece \"League of Legends\"?", options: ["MMORPG", "MOBA", "RTS", "Battle royale"], answerIndex: 1},
    {q: "¿Qué juego de FromSoftware ganó el premio al Juego del Año en 2022?", options: ["Sekiro", "Bloodborne", "Elden Ring", "Dark Souls III"], answerIndex: 2},
    {q: "¿Qué compañía desarrolló originalmente la saga \"Halo\"?", options: ["343 Industries", "Epic Games", "id Software", "Bungie"], answerIndex: 3},
    {q: "¿Qué juego de Nintendo permite construir una isla habitada por vecinos animales?", options: ["Animal Crossing", "Harvest Moon", "Pikmin", "Nintendogs"], answerIndex: 0},
    {q: "¿Qué battle royale de Respawn se ambienta en el universo de Titanfall?", options: ["Warzone", "Apex Legends", "Fortnite", "Blackout"], answerIndex: 1},
    {q: "¿Qué saga de rol de Square Enix protagoniza Cloud Strife?", options: ["Dragon Quest", "Kingdom Hearts", "Final Fantasy", "Chrono"], answerIndex: 2},
    {q: "¿Qué juego de simulación de granja fue creado casi por completo por ConcernedApe?", options: ["Farming Simulator", "My Time at Portia", "Graveyard Keeper", "Stardew Valley"], answerIndex: 3},
    {q: "¿Qué juego de 1996 llevó a Mario al mundo tridimensional?", options: ["Super Mario 64", "Super Mario Sunshine", "Super Mario World", "Super Mario Galaxy"], answerIndex: 0},
    {q: "¿Cuál es la consola más vendida en la historia de PlayStation?", options: ["PlayStation 1", "PlayStation 2", "PlayStation 4", "PlayStation 3"], answerIndex: 1},
    {q: "¿Qué saga de fútbol de Konami competía históricamente con FIFA?", options: ["Football Manager", "Sensible Soccer", "Pro Evolution Soccer", "Kick Off"], answerIndex: 2},
    {q: "¿Qué juego de Rockstar transcurre en Liberty City con Niko Bellic?", options: ["GTA V", "GTA: San Andreas", "GTA: Vice City", "GTA IV"], answerIndex: 3},
    {q: "¿Qué shooter competitivo de Valve enfrenta a terroristas y antiterroristas?", options: ["Counter-Strike", "Valorant", "Rainbow Six Siege", "Call of Duty"], answerIndex: 0},
    {q: "¿Qué saga de Ubisoft protagoniza el pirata Edward Kenway?", options: ["Far Cry", "Assassin's Creed", "Watch Dogs", "Prince of Persia"], answerIndex: 1},
    {q: "¿Qué juego de Capcom con Leon y Claire recibió un aclamado remake en 2019?", options: ["Resident Evil 3", "Resident Evil 4", "Resident Evil 2", "Resident Evil 7"], answerIndex: 2},
  ],

  d3: [
    {q: "¿Qué videojuego de 1985 impulsó la recuperación de la industria tras la crisis de 1983?", options: ["Super Mario Bros.", "The Legend of Zelda", "Metroid", "Duck Hunt"], answerIndex: 0},
    {q: "¿Qué juego de Atari de 1972 fue el primer gran éxito comercial de la industria?", options: ["Breakout", "Pong", "Asteroids", "Centipede"], answerIndex: 1},
    {q: "¿Qué diseñador creó \"SimCity\" y \"The Sims\"?", options: ["Peter Molyneux", "Sid Meier", "Will Wright", "Richard Garriott"], answerIndex: 2},
    {q: "¿Qué compañía japonesa desarrolló \"Chrono Trigger\" en 1995?", options: ["Enix", "Konami", "Namco", "Square"], answerIndex: 3},
    {q: "¿Qué juego de Nintendo 64 de 1998 es considerado uno de los mejores de la historia?", options: ["Ocarina of Time", "GoldenEye 007", "Banjo-Kazooie", "Perfect Dark"], answerIndex: 0},
    {q: "¿Qué motor gráfico desarrolla Unity Technologies?", options: ["CryEngine", "Unity", "Godot", "Source"], answerIndex: 1},
    {q: "¿Qué juego de id Software de 1993 popularizó el shooter en primera persona?", options: ["Wolfenstein 3D", "Quake", "Doom", "Duke Nukem 3D"], answerIndex: 2},
    {q: "¿Qué programador cofundó id Software y es célebre por sus motores 3D?", options: ["Gabe Newell", "Tim Sweeney", "John Romero", "John Carmack"], answerIndex: 3},
    {q: "¿Cuál fue la última consola doméstica fabricada por Sega?", options: ["Dreamcast", "Saturn", "Mega Drive", "Master System"], answerIndex: 0},
    {q: "¿Qué diseñador creó la saga de estrategia \"Civilization\"?", options: ["Will Wright", "Sid Meier", "Bruce Shelley", "Chris Taylor"], answerIndex: 1},
    {q: "¿Qué juego de rol de BioWare está ambientado en el universo de Star Wars?", options: ["Mass Effect", "Jade Empire", "Knights of the Old Republic", "Baldur's Gate"], answerIndex: 2},
    {q: "¿Qué juego japonés de Taito de 1978 impulsó la era dorada de los arcades?", options: ["Galaga", "Defender", "Asteroids", "Space Invaders"], answerIndex: 3},
    {q: "¿Qué estudio japonés desarrolló \"Shadow of the Colossus\"?", options: ["Team Ico", "Platinum Games", "Grasshopper Manufacture", "Clover Studio"], answerIndex: 0},
    {q: "¿Qué estudio desarrolla la saga de simulación de conducción \"Gran Turismo\"?", options: ["Evolution Studios", "Polyphony Digital", "Bizarre Creations", "Codemasters"], answerIndex: 1},
    {q: "¿Qué término designa un juego gratuito que se financia con compras dentro de la aplicación?", options: ["Shareware", "Early access", "Free-to-play", "Season pass"], answerIndex: 2},
    {q: "¿Qué diseñador japonés es considerado el creador de la saga \"Sonic\"?", options: ["Shigeru Miyamoto", "Hideo Kojima", "Yu Suzuki", "Yuji Naka"], answerIndex: 3},
    {q: "¿Qué crisis estuvo a punto de hundir a la industria de los videojuegos en Norteamérica?", options: ["La crisis de 1983", "La burbuja de 1995", "El crac de 1977", "La recesión de 1990"], answerIndex: 0},
  ],
};
