module.exports = {
  d1: [
    {q: "¿De qué color es la gorra de Mario?", options: ["Verde", "Azul", "Roja", "Amarilla"], answerIndex: 2},
    {q: "¿Cómo se llama el hermano de Mario?", options: ["Toad", "Wario", "Waluigi", "Luigi"], answerIndex: 3},
    {q: "¿Qué Pokémon amarillo de tipo eléctrico es la mascota de la saga?", options: ["Pikachu", "Charmander", "Squirtle", "Bulbasaur"], answerIndex: 0},
    {q: "¿Qué juego consiste en encajar piezas geométricas que caen desde arriba?", options: ["Bejeweled", "Tetris", "Pac-Man", "Candy Crush"], answerIndex: 1},
    {q: "¿Cómo se llama la princesa que Mario suele rescatar?", options: ["Peach", "Zelda", "Daisy", "Rosalina"], answerIndex: 0},
    {q: "¿Qué tipo de animal es Sonic?", options: ["Una ardilla", "Un ratón", "Un zorro", "Un erizo"], answerIndex: 3},
    {q: "¿Cómo se llama el dinosaurio verde que acompaña a Mario?", options: ["Yoshi", "Bowser", "Goomba", "Koopa"], answerIndex: 0},
    {q: "¿Qué saga de Nintendo consiste en carreras de karts?", options: ["Mario Tennis", "Mario Golf", "Mario Kart", "Mario Party"], answerIndex: 2},
    {q: "¿En qué videojuego se juega al fútbol conduciendo automóviles?", options: ["FIFA Street", "Trackmania", "Fall Guys", "Rocket League"], answerIndex: 3},
    {q: "¿Qué saga de lucha incluye a Ryu y Chun-Li?", options: ["King of Fighters", "Tekken", "Street Fighter", "Mortal Kombat"], answerIndex: 2},
    {q: "¿Qué consola portátil de Nintendo se caracterizaba por tener dos pantallas?", options: ["PSP", "Nintendo DS", "Game Gear", "Game Boy"], answerIndex: 1},
    {q: "¿Qué significan las siglas \"RPG\" en los videojuegos?", options: ["Juego de carreras", "Juego de disparos", "Juego de rol", "Juego de estrategia"], answerIndex: 2},
    {q: "¿Con qué dispositivo se juega normalmente en una consola?", options: ["La tableta", "El ratón", "El mando", "El micrófono"], answerIndex: 2},
    {q: "¿Qué juego de disparos por equipos de Blizzard incluye a la heroína Tracer?", options: ["Paladins", "Overwatch", "Valorant", "Team Fortress"], answerIndex: 1},
    {q: "¿Qué enemigo con caparazón y cuernos es el villano principal de Mario?", options: ["King Boo", "Kamek", "Bowser", "Donkey Kong"], answerIndex: 2},
    {q: "¿Qué saga de Nintendo protagoniza una cazarrecompensas llamada Samus Aran?", options: ["F-Zero", "Metroid", "Star Fox", "Kirby"], answerIndex: 1},
  ],

  d2: [
    {q: "¿Qué estudio desarrolló la saga \"God of War\"?", options: ["Sucker Punch", "Guerrilla Games", "Insomniac Games", "Santa Monica Studio"], answerIndex: 3},
    {q: "¿Qué juego de 2017 renovó la saga Zelda con un enorme mundo abierto?", options: ["Twilight Princess", "Skyward Sword", "Breath of the Wild", "A Link Between Worlds"], answerIndex: 2},
    {q: "¿En qué ciudad ficticia transcurre \"Cyberpunk 2077\"?", options: ["Rapture", "Neo Tokio", "Night City", "Midgar"], answerIndex: 2},
    {q: "¿Qué saga de Bethesda transcurre en un mundo postnuclear con refugios llamados Vault?", options: ["Fallout", "Wasteland", "BioShock", "Metro"], answerIndex: 0},
    {q: "¿Qué juego de rol de Bethesda transcurre en la región de Skyrim?", options: ["Divinity", "Gothic", "Dragon Age", "The Elder Scrolls V"], answerIndex: 3},
    {q: "¿Qué compañía desarrolló \"Overwatch\"?", options: ["Valve", "Bungie", "Blizzard", "Riot Games"], answerIndex: 2},
    {q: "¿Qué saga de estrategia en tiempo real de Blizzard enfrenta a orcos y humanos?", options: ["Warcraft", "Command & Conquer", "Total War", "Age of Empires"], answerIndex: 0},
    {q: "¿Qué videojuego de Valve se basa en resolver puzles con un arma que crea portales?", options: ["The Talos Principle", "Antichamber", "Portal", "Half-Life"], answerIndex: 2},
    {q: "¿Qué plataforma digital de distribución de juegos para PC creó Valve?", options: ["Steam", "Origin", "Epic Games Store", "GOG"], answerIndex: 0},
    {q: "¿Qué saga de Konami protagoniza el soldado Solid Snake?", options: ["Hitman", "Metal Gear Solid", "Splinter Cell", "Syphon Filter"], answerIndex: 1},
    {q: "¿Qué juego de Nintendo enfrenta en combate a personajes de distintas sagas?", options: ["Nintendo Land", "Super Smash Bros.", "Mario Party", "Wii Sports"], answerIndex: 1},
    {q: "¿Qué juego indie de plataformas protagoniza un insecto en el reino de Hallownest?", options: ["Celeste", "Hollow Knight", "Ori and the Blind Forest", "Dead Cells"], answerIndex: 1},
    {q: "¿Qué compañía desarrolló \"League of Legends\"?", options: ["Tencent Games", "Valve", "Riot Games", "Blizzard"], answerIndex: 2},
    {q: "¿A qué género pertenece \"League of Legends\"?", options: ["MMORPG", "RTS", "MOBA", "Battle royale"], answerIndex: 2},
    {q: "¿Qué juego de FromSoftware ganó el premio al Juego del Año en 2022?", options: ["Bloodborne", "Sekiro", "Dark Souls III", "Elden Ring"], answerIndex: 3},
    {q: "¿Qué compañía desarrolló originalmente la saga \"Halo\"?", options: ["id Software", "Bungie", "343 Industries", "Epic Games"], answerIndex: 1},
    {q: "¿Qué juego de Nintendo permite construir una isla habitada por vecinos animales?", options: ["Pikmin", "Harvest Moon", "Nintendogs", "Animal Crossing"], answerIndex: 3},
    {q: "¿Qué battle royale de Respawn se ambienta en el universo de Titanfall?", options: ["Blackout", "Apex Legends", "Fortnite", "Warzone"], answerIndex: 1},
    {q: "¿Qué saga de rol de Square Enix protagoniza Cloud Strife?", options: ["Chrono", "Dragon Quest", "Final Fantasy", "Kingdom Hearts"], answerIndex: 2},
    {q: "¿Qué juego de simulación de granja fue creado casi por completo por ConcernedApe?", options: ["Farming Simulator", "Stardew Valley", "My Time at Portia", "Graveyard Keeper"], answerIndex: 1},
    {q: "¿Qué juego de 1996 llevó a Mario al mundo tridimensional?", options: ["Super Mario Galaxy", "Super Mario Sunshine", "Super Mario World", "Super Mario 64"], answerIndex: 3},
    {q: "¿Cuál es la consola más vendida en la historia de PlayStation?", options: ["PlayStation 4", "PlayStation 2", "PlayStation 1", "PlayStation 3"], answerIndex: 1},
    {q: "¿Qué saga de fútbol de Konami competía históricamente con FIFA?", options: ["Football Manager", "Sensible Soccer", "Pro Evolution Soccer", "Kick Off"], answerIndex: 2},
    {q: "¿Qué juego de Rockstar transcurre en Liberty City con Niko Bellic?", options: ["GTA IV", "GTA: Vice City", "GTA V", "GTA: San Andreas"], answerIndex: 0},
    {q: "¿Qué shooter competitivo de Valve enfrenta a terroristas y antiterroristas?", options: ["Counter-Strike", "Valorant", "Rainbow Six Siege", "Call of Duty"], answerIndex: 0},
    {q: "¿Qué saga de Ubisoft protagoniza el pirata Edward Kenway?", options: ["Prince of Persia", "Assassin's Creed", "Watch Dogs", "Far Cry"], answerIndex: 1},
    {q: "¿Qué juego de Capcom con Leon y Claire recibió un aclamado remake en 2019?", options: ["Resident Evil 2", "Resident Evil 7", "Resident Evil 3", "Resident Evil 4"], answerIndex: 0},
  ],

  d3: [
    {q: "¿Qué videojuego de 1985 impulsó la recuperación de la industria tras la crisis de 1983?", options: ["Duck Hunt", "The Legend of Zelda", "Metroid", "Super Mario Bros."], answerIndex: 3},
    {q: "¿Qué juego de Atari de 1972 fue el primer gran éxito comercial de la industria?", options: ["Centipede", "Pong", "Asteroids", "Breakout"], answerIndex: 1},
    {q: "¿Qué diseñador creó \"SimCity\" y \"The Sims\"?", options: ["Richard Garriott", "Will Wright", "Peter Molyneux", "Sid Meier"], answerIndex: 1},
    {q: "¿Qué compañía japonesa desarrolló \"Chrono Trigger\" en 1995?", options: ["Namco", "Square", "Konami", "Enix"], answerIndex: 1},
    {q: "¿Qué juego de Nintendo 64 de 1998 es considerado uno de los mejores de la historia?", options: ["Ocarina of Time", "Banjo-Kazooie", "Perfect Dark", "GoldenEye 007"], answerIndex: 0},
    {q: "¿Qué motor gráfico desarrolla Unity Technologies?", options: ["CryEngine", "Godot", "Source", "Unity"], answerIndex: 3},
    {q: "¿Qué juego de id Software de 1993 popularizó el shooter en primera persona?", options: ["Quake", "Wolfenstein 3D", "Doom", "Duke Nukem 3D"], answerIndex: 2},
    {q: "¿Qué programador cofundó id Software y es célebre por sus motores 3D?", options: ["Gabe Newell", "John Carmack", "John Romero", "Tim Sweeney"], answerIndex: 1},
    {q: "¿Cuál fue la última consola doméstica fabricada por Sega?", options: ["Dreamcast", "Master System", "Mega Drive", "Saturn"], answerIndex: 0},
    {q: "¿Qué diseñador creó la saga de estrategia \"Civilization\"?", options: ["Chris Taylor", "Bruce Shelley", "Sid Meier", "Will Wright"], answerIndex: 2},
    {q: "¿Qué juego de rol de BioWare está ambientado en el universo de Star Wars?", options: ["Knights of the Old Republic", "Baldur's Gate", "Jade Empire", "Mass Effect"], answerIndex: 0},
    {q: "¿Qué juego japonés de Taito de 1978 impulsó la era dorada de los arcades?", options: ["Asteroids", "Space Invaders", "Galaga", "Defender"], answerIndex: 1},
    {q: "¿Qué estudio japonés desarrolló \"Shadow of the Colossus\"?", options: ["Grasshopper Manufacture", "Platinum Games", "Team Ico", "Clover Studio"], answerIndex: 2},
    {q: "¿Qué estudio desarrolla la saga de simulación de conducción \"Gran Turismo\"?", options: ["Polyphony Digital", "Evolution Studios", "Bizarre Creations", "Codemasters"], answerIndex: 0},
    {q: "¿Qué término designa un juego gratuito que se financia con compras dentro de la aplicación?", options: ["Free-to-play", "Early access", "Season pass", "Shareware"], answerIndex: 0},
    {q: "¿Qué diseñador japonés es considerado el creador de la saga \"Sonic\"?", options: ["Hideo Kojima", "Yu Suzuki", "Shigeru Miyamoto", "Yuji Naka"], answerIndex: 3},
    {q: "¿Qué crisis estuvo a punto de hundir a la industria de los videojuegos en Norteamérica?", options: ["La burbuja de 1995", "El crac de 1977", "La recesión de 1990", "La crisis de 1983"], answerIndex: 3},
  ],
};
